export type { Role, OrgType, ProjectStatus, Organization, User, Project } from "@/types/project";
import type { InboxThread } from "@/types/inbox";
import type { KbAnswer, KbIndexHealth } from "@/types/knowledge";
import type { Organization, User, Project } from "@/types/project";

// Legacy aliases — kept while other pages migrate to @/types/*
export type MockOrganization = Organization;
export type MockUser = User;
export type MockProject = Project;

export const MOCK_ORG: Organization = {
  id: "org_maple_001",
  name: "Maple Therapeutics",
  type: "BIOTECH",
  dataResidency: "uk",
};

export const MOCK_USER: User = {
  id: "user_priya_001",
  name: "Priya Shah",
  email: "priya.shah@mapletherapeutics.com",
  role: "ra_lead",
  title: "Regulatory Affairs",
  initials: "PS",
  organizationId: MOCK_ORG.id,
};

// ── Projects ──────────────────────────────────────────────────────────────────

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj_map_204",
    code: "MAP-204",
    title: "Onaplazib in NASH",
    phase: "Phase II",
    indication: "Hepatology",
    regions: ["UK", "US", "DE"],
    status: "RECRUITING",
    targetEnrolment: 320,
    actualEnrolment: 198,
    siteCount: 28,
    openItems: 4,
    ownerId: "user_priya_001",
    ownerName: "Priya Shah",
    ownerInitials: "PS",
    ownerColor: "oklch(58% 0.10 185)",
    organizationId: "org_maple_001",
    startDate: "2023-03-01",
    endDate: "2026-06-01",
  },
  {
    id: "proj_map_117",
    code: "MAP-117",
    title: "Selvaxin combo, EGFRm NSCLC",
    phase: "Phase Ib",
    indication: "Oncology",
    regions: ["UK", "US"],
    status: "PRE_IND",
    targetEnrolment: 84,
    actualEnrolment: 0,
    siteCount: 6,
    openItems: 7,
    ownerId: "user_remi_001",
    ownerName: "Remi Okafor",
    ownerInitials: "RO",
    ownerColor: "oklch(55% 0.14 260)",
    organizationId: "org_maple_001",
    startDate: "2025-09-01",
    endDate: "2028-03-01",
  },
  {
    id: "proj_map_003",
    code: "MAP-003",
    title: "Paediatric AAV gene therapy",
    phase: "Phase III",
    indication: "Rare disease",
    regions: ["UK", "NL"],
    status: "IN_SCREENING",
    targetEnrolment: 24,
    actualEnrolment: 5,
    siteCount: 4,
    openItems: 2,
    ownerId: "user_marta_001",
    ownerName: "Marta Kovacs",
    ownerInitials: "MK",
    ownerColor: "oklch(62% 0.13 55)",
    organizationId: "org_maple_001",
    startDate: "2024-11-01",
    endDate: "2027-05-01",
  },
  {
    id: "proj_rap_089",
    code: "RAP-089",
    title: "TNFα blocker — psoriatic arthritis",
    phase: "Phase III",
    indication: "Immunology",
    regions: ["UK", "EU", "US", "CA"],
    status: "IN_FOLLOW_UP",
    targetEnrolment: 612,
    actualEnrolment: 575,
    siteCount: 61,
    openItems: 1,
    ownerId: "user_arjun_001",
    ownerName: "Arjun Patel",
    ownerInitials: "AP",
    ownerColor: "oklch(55% 0.14 210)",
    organizationId: "org_maple_001",
    startDate: "2021-06-01",
    endDate: "2026-09-01",
  },
  {
    id: "proj_rap_156",
    code: "RAP-156",
    title: "Cardiac biomarker dx study",
    phase: "Observational",
    indication: "Cardiovascular",
    regions: ["UK"],
    status: "RECRUITING",
    targetEnrolment: 1200,
    actualEnrolment: 576,
    siteCount: 14,
    openItems: 0,
    ownerId: "user_li_001",
    ownerName: "Li Tan",
    ownerInitials: "LT",
    ownerColor: "oklch(55% 0.12 145)",
    organizationId: "org_maple_001",
    startDate: "2024-01-01",
    endDate: "2027-01-01",
  },
  {
    id: "proj_map_301",
    code: "MAP-301",
    title: "Long COVID natural history",
    phase: "Observational",
    indication: "Infectious disease",
    regions: ["UK"],
    status: "REPORTING",
    targetEnrolment: 850,
    actualEnrolment: 850,
    siteCount: 22,
    openItems: 3,
    ownerId: "user_priya_001",
    ownerName: "Priya Shah",
    ownerInitials: "PS",
    ownerColor: "oklch(58% 0.10 185)",
    organizationId: "org_maple_001",
    startDate: "2022-01-01",
    endDate: "2025-12-01",
  },
  {
    id: "proj_map_811",
    code: "MAP-811",
    title: "Bispecific Ab — refractory AML",
    phase: "Phase I",
    indication: "Oncology",
    regions: ["UK", "DE"],
    status: "RECRUITING",
    targetEnrolment: 36,
    actualEnrolment: 30,
    siteCount: 5,
    openItems: 2,
    ownerId: "user_remi_001",
    ownerName: "Remi Okafor",
    ownerInitials: "RO",
    ownerColor: "oklch(55% 0.14 260)",
    organizationId: "org_maple_001",
    startDate: "2025-02-01",
    endDate: "2026-08-01",
  },
  {
    id: "proj_map_812",
    code: "MAP-812",
    title: "Bone marrow conditioning regimen",
    phase: "Phase II",
    indication: "Haematology",
    regions: ["UK"],
    status: "DRAFT",
    targetEnrolment: 90,
    actualEnrolment: 0,
    siteCount: 3,
    openItems: 5,
    ownerId: "user_marta_001",
    ownerName: "Marta Kovacs",
    ownerInitials: "MK",
    ownerColor: "oklch(62% 0.13 55)",
    organizationId: "org_maple_001",
    startDate: "2026-09-01",
    endDate: "2029-03-01",
  },
  {
    id: "proj_map_445",
    code: "MAP-445",
    title: "NASH fibrosis reversal study",
    phase: "Phase II",
    indication: "Hepatology",
    regions: ["UK", "US", "FR"],
    status: "RECRUITING",
    targetEnrolment: 200,
    actualEnrolment: 87,
    siteCount: 12,
    openItems: 0,
    ownerId: "user_priya_001",
    ownerName: "Priya Shah",
    ownerInitials: "PS",
    ownerColor: "oklch(58% 0.10 185)",
    organizationId: "org_maple_001",
    startDate: "2024-06-01",
    endDate: "2027-06-01",
  },
  {
    id: "proj_rap_290",
    code: "RAP-290",
    title: "PD-L1 inhibitor combo NSCLC",
    phase: "Phase II",
    indication: "Oncology",
    regions: ["UK", "US", "DE", "AU"],
    status: "IN_SCREENING",
    targetEnrolment: 450,
    actualEnrolment: 0,
    siteCount: 8,
    openItems: 3,
    ownerId: "user_arjun_001",
    ownerName: "Arjun Patel",
    ownerInitials: "AP",
    ownerColor: "oklch(55% 0.14 210)",
    organizationId: "org_maple_001",
    startDate: "2025-11-01",
    endDate: "2029-05-01",
  },
  {
    id: "proj_map_509",
    code: "MAP-509",
    title: "HER2+ breast cancer neoadjuvant",
    phase: "Phase II",
    indication: "Oncology",
    regions: ["UK", "EU"],
    status: "RECRUITING",
    targetEnrolment: 180,
    actualEnrolment: 142,
    siteCount: 19,
    openItems: 1,
    ownerId: "user_remi_001",
    ownerName: "Remi Okafor",
    ownerInitials: "RO",
    ownerColor: "oklch(55% 0.14 260)",
    organizationId: "org_maple_001",
    startDate: "2023-08-01",
    endDate: "2026-02-01",
  },
  {
    id: "proj_rap_044",
    code: "RAP-044",
    title: "Omega-3 cardiovascular protection",
    phase: "Phase III",
    indication: "Cardiovascular",
    regions: ["UK", "US"],
    status: "IN_FOLLOW_UP",
    targetEnrolment: 3500,
    actualEnrolment: 3240,
    siteCount: 45,
    openItems: 0,
    ownerId: "user_li_001",
    ownerName: "Li Tan",
    ownerInitials: "LT",
    ownerColor: "oklch(55% 0.12 145)",
    organizationId: "org_maple_001",
    startDate: "2020-04-01",
    endDate: "2026-10-01",
  },
  {
    id: "proj_map_712",
    code: "MAP-712",
    title: "CRISPR sickle-cell correction",
    phase: "Phase I",
    indication: "Haematology",
    regions: ["UK"],
    status: "DRAFT",
    targetEnrolment: 30,
    actualEnrolment: 0,
    siteCount: 2,
    openItems: 8,
    ownerId: "user_marta_001",
    ownerName: "Marta Kovacs",
    ownerInitials: "MK",
    ownerColor: "oklch(62% 0.13 55)",
    organizationId: "org_maple_001",
    startDate: "2027-01-01",
    endDate: "2029-12-01",
  },
  {
    id: "proj_rap_221",
    code: "RAP-221",
    title: "Anti-IL-17 in plaque psoriasis",
    phase: "Phase III",
    indication: "Dermatology",
    regions: ["UK", "EU", "US"],
    status: "COMPLETED",
    targetEnrolment: 612,
    actualEnrolment: 612,
    siteCount: 38,
    openItems: 0,
    ownerId: "user_arjun_001",
    ownerName: "Arjun Patel",
    ownerInitials: "AP",
    ownerColor: "oklch(55% 0.14 210)",
    organizationId: "org_maple_001",
    startDate: "2019-06-01",
    endDate: "2024-12-01",
  },
];

// ── Inbox ──────────────────────────────────────────────────────────────────────

export const MOCK_INBOX_THREADS: InboxThread[] = [
  {
    id: "thread_001",
    kind: "review",
    sender: "R. Okafor",
    senderInitials: "RO",
    senderColor: "oklch(55% 0.14 260)",
    subject: "Protocol v3 ready for your review — MAP-117",
    snippet: "Hi Priya, I've completed the Phase Ib dose-escalation section and flagged the MHRA CTA points for your sign-off…",
    domainTag: "Protocol",
    studyCode: "MAP-117",
    urgency: "urgent",
    age: "12 min",
    isUnread: true,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_001a",
        from: "Remi Okafor",
        fromInitials: "RO",
        fromColor: "oklch(55% 0.14 260)",
        body: "Hi Priya,\n\nI've completed the Phase Ib dose-escalation section for MAP-117 (Selvaxin combo, EGFRm NSCLC) and uploaded Protocol v3. The AI flagged two potential ICH E6(R3) gaps in Section 4.2 — specifically around the stopping rules for DLT Grade ≥3. I've annotated these with citations from FDA guidance but I'd appreciate your sign-off before we submit the CTA to MHRA.\n\nI've also drafted the eligibility exclusion criteria based on the prior Phase Ia data — please review criterion 7 (prior EGFR TKI therapy) as the confidence score is 62%, just above the threshold.\n\nCould you review and approve by EOD Thursday? The MHRA pre-submission slot is Friday 09:00.",
        age: "12 min",
      },
    ],
  },
  {
    id: "thread_002",
    kind: "regulator",
    sender: "MHRA · ILAP",
    senderInitials: "MH",
    subject: "ILAP target development profile — MAP-204 Type II variation",
    snippet: "Your Innovative Licensing and Access Pathway application for MAP-204 has been assigned to a product specialist. Next steps: submit updated TDP by 4 July…",
    domainTag: "Regulator",
    studyCode: "MAP-204",
    urgency: "high",
    age: "1h",
    isUnread: true,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_002a",
        from: "MHRA · ILAP Team",
        fromInitials: "MH",
        body: "Dear Maple Therapeutics,\n\nYour Innovative Licensing and Access Pathway (ILAP) application for MAP-204 (Onaplazib, NASH) has been reviewed by the MHRA and assigned to a designated product specialist.\n\nRequired action: Please submit an updated Target Development Profile (TDP) reflecting the Phase II interim data (data cut: 31 May 2026) no later than 4 July 2026. The updated TDP should address the hepatic safety signal raised at the last Coordination Group meeting.\n\nA Scientific Advice meeting has been provisionally booked for 18 July 2026. Dial-in details will follow separately.\n\nPlease confirm receipt of this communication within 5 working days.",
        age: "1h",
      },
    ],
  },
  {
    id: "thread_003",
    kind: "mention",
    sender: "L. Tan",
    senderInitials: "LT",
    senderColor: "oklch(55% 0.12 145)",
    subject: "@Priya — eligibility query on RAP-156 cardiac biomarker criteria",
    snippet: "@Priya, I've flagged criterion 4 (eGFR threshold) against the 2025 NICE guidance update. The AI confidence is 71% — below your usual threshold. Can you review?",
    domainTag: "Eligibility",
    studyCode: "RAP-156",
    urgency: "normal",
    age: "2h",
    isUnread: true,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_003a",
        from: "Li Tan",
        fromInitials: "LT",
        fromColor: "oklch(55% 0.12 145)",
        body: "@Priya\n\nQuick query on the RAP-156 inclusion criterion 4 (eGFR ≥45 mL/min/1.73m²). The AI has cross-referenced this against the 2025 NICE CG182 update and flagged a potential discrepancy — the updated guidance recommends ≥50 for the cardiac biomarker population we're targeting, particularly in patients with concurrent ACE inhibitor use.\n\nConfidence on this criterion is 71% — below the 85% green threshold. I've attached the relevant NICE passage and the prior MAP-156 precedent.\n\nShould we revise criterion 4 before the next site initiation visit on 30 June?",
        age: "2h",
      },
    ],
  },
  {
    id: "thread_004",
    kind: "safety_flag",
    sender: "AI · Cohortly",
    senderInitials: "AI",
    subject: "Safety flag — SAE cluster detected, MAP-204 hepatic events",
    snippet: "Automated signal detection has identified a potential cluster of Grade 2+ hepatic AEs (n=4, 28 days). PRR 3.2, χ² 8.1. Enhanced review recommended…",
    domainTag: "Safety",
    studyCode: "MAP-204",
    urgency: "urgent",
    age: "3h",
    isUnread: true,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_004a",
        from: "AI · Cohortly",
        fromInitials: "AI",
        body: "Automated safety signal detection has identified a potential cluster of Grade 2 or higher hepatic adverse events in MAP-204 (Onaplazib, NASH) over a rolling 28-day window.\n\nSignal summary:\n• Events: 4 Grade 2+ hepatic AEs (ALT/AST elevation)\n• Proportional Reporting Ratio (PRR): 3.2 (threshold: 2.0)\n• χ² statistic: 8.1 (threshold: 4.0)\n• MedDRA PT: Drug-induced liver injury (10072268)\n\nThis signal exceeds the pre-defined pharmacovigilance thresholds configured for MAP-204. Under the MAP-204 Risk Management Plan (v2.1), a hepatic safety monitoring review is required within 5 working days.\n\nRecommended actions: (1) Review individual SAE narratives for the 4 subjects. (2) Assess against the DSMB charter stopping rules. (3) Notify the Principal Investigator at UCL site.\n\nThis flag has been added to the Safety & PV queue. Confidence: 0.89 · Model: cohortly-safety-v2 · Retrieved from: MAP-204 RMP v2.1, ICH E2A.",
        age: "3h",
      },
    ],
  },
  {
    id: "thread_005",
    kind: "regulator",
    sender: "HRA · REC",
    senderInitials: "HR",
    subject: "REC opinion issued — MAP-003 paediatric amendment 3",
    snippet: "The Research Ethics Committee has issued a Favourable Opinion for Amendment 3 to MAP-003. One condition attached: revised PIS (plain English summary) required within 28 days…",
    domainTag: "Ethics",
    studyCode: "MAP-003",
    urgency: "high",
    age: "4h",
    isUnread: false,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_005a",
        from: "HRA · South Central — Oxford C REC",
        fromInitials: "HR",
        body: "Dear Chief Investigator,\n\nThe Research Ethics Committee has reviewed Amendment 3 to MAP-003 (Paediatric AAV gene therapy) at its meeting on 19 June 2026 and has issued a Favourable Opinion.\n\nCondition: The Committee requests a revised Patient Information Sheet (PIS) and Assent Form for the 8–11 age group. The current readability score (Flesch-Kincaid Grade 7.2) exceeds the recommended maximum of Grade 6 for this age group. Please resubmit the revised PIS within 28 days.\n\nThe Favourable Opinion reference is: 26/SC/0142/AM03. Please quote this on all correspondence.\n\nYou may proceed with the amendment in line with your response once the condition is satisfied.",
        age: "4h",
      },
    ],
  },
  {
    id: "thread_006",
    kind: "regulator",
    sender: "FDA · CDER",
    senderInitials: "FD",
    subject: "IND 149-228 — Information Request re: MAP-204 hepatic safety data",
    snippet: "Reference your IND 149-228. CDER requests additional hepatic histopathology data from the 12-week preclinical study (Study RD-2024-07) within 30 days…",
    domainTag: "Regulator",
    studyCode: "MAP-204",
    urgency: "urgent",
    age: "Yesterday",
    isUnread: false,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_006a",
        from: "FDA · CDER Division of Hepatology",
        fromInitials: "FD",
        body: "RE: IND 149-228, Onaplazib (MAP-204), Information Request\n\nDear Sponsor,\n\nDuring its review of your IND Annual Report (submitted 1 June 2026), the Division identified the need for additional data to complete its assessment of the hepatic safety profile of Onaplazib.\n\nSpecifically, CDER requests:\n1. Full hepatic histopathology tables from the 12-week rat repeat-dose study (Study RD-2024-07), including individual animal data.\n2. Bridging analysis comparing preclinical ALT/AST elevations to the clinical Grade 2+ events reported in the Phase II interim.\n3. Proposed hepatic monitoring algorithm for the remainder of the Phase II study.\n\nThis information must be submitted within 30 days of the date of this letter (by 23 July 2026). Failure to respond may result in a clinical hold.",
        age: "Yesterday",
      },
    ],
  },
  {
    id: "thread_007",
    kind: "review",
    sender: "M. Kovacs",
    senderInitials: "MK",
    senderColor: "oklch(62% 0.13 55)",
    subject: "IRAS amendment 3 ready for QA sign-off — MAP-003",
    snippet: "Marta Kovacs assigned you as QA reviewer on IRAS amendment 3 for MAP-003. Completion 94%, 1 section flagged for manual review (Section E, gene therapy-specific questions)…",
    domainTag: "Ethics",
    studyCode: "MAP-003",
    urgency: "normal",
    age: "2d",
    isUnread: false,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_007a",
        from: "Marta Kovacs",
        fromInitials: "MK",
        fromColor: "oklch(62% 0.13 55)",
        body: "Hi Priya,\n\nI've assigned you as QA reviewer on IRAS Amendment 3 for MAP-003. The AI has auto-populated 94% of the form using the approved protocol and the REC correspondence. One section needs manual review:\n\n• Section E (Advanced Therapy Medicinal Products) — the AAV serotype-specific questions (E7–E9) require manual input as these aren't covered in the KB yet. I've drafted placeholder answers but confidence scores are 41–55%, well below threshold.\n\nEverything else (Sections A–D, F–H) is complete with confidence ≥82%. The application is otherwise ready for submission pending your sign-off on Section E.\n\nCan you review by end of play Friday?",
        age: "2d",
      },
    ],
  },
  {
    id: "thread_008",
    kind: "mention",
    sender: "A. Patel",
    senderInitials: "AP",
    senderColor: "oklch(55% 0.14 210)",
    subject: "@Priya — RAP-089 CTD 2.7.4 summary needs your input",
    snippet: "@Priya could you review the immunogenicity section of the RAP-089 CTD 2.7.4 clinical summary? The AI draft has 3 unverified citations from the EMA CHMP assessment report…",
    domainTag: "Reg Writing",
    studyCode: "RAP-089",
    urgency: "normal",
    age: "3d",
    isUnread: false,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_008a",
        from: "Arjun Patel",
        fromInitials: "AP",
        fromColor: "oklch(55% 0.14 210)",
        body: "@Priya\n\nThe AI-drafted immunogenicity section (CTD 2.7.4.3) for RAP-089 has 3 citations flagged as unverified — they reference the EMA CHMP Assessment Report for the reference biologic (adalimumab), but the KB doesn't have the full PDF indexed yet (only the public summary). The citation confidence on those 3 statements is 48–55%.\n\nI've highlighted the passages in the document. Options: (1) We pause and get the CHMP full report indexed (2–3 days), (2) I manually verify and annotate them, (3) we rephrase to cite the public summary only.\n\nWhat's your preference? The EMA submission window is 15 July.",
        age: "3d",
      },
    ],
  },
];

// ── Knowledge Base ─────────────────────────────────────────────────────────────

export const SAMPLE_KB_ANSWER: KbAnswer = {
  query: "When is a DSMB required for a Phase II NASH trial in the UK?",
  confidence: 92,
  sourceCount: 4,
  latencyMs: 730,
  modelVersion: "cohort-v3",
  segments: [
    { type: "text", value: "A DSMB is " },
    { type: "text", value: "required" },
    { type: "text", value: " for Phase II NASH trials in the UK when the trial enrolls vulnerable populations or where the intervention carries non-negligible safety risk " },
    {
      type: "citation",
      value: "[1]",
      citationRef: { n: 1, sourceId: "src_fda_dsmb_2024", label: "FDA DSMB Guidance" },
    },
    { type: "text", value: ". For NASH specifically, the FDA's 2023 guidance and EMA's SAWP minutes recommend independent safety oversight given the hepatic toxicity considerations " },
    {
      type: "citation",
      value: "[2]",
      citationRef: { n: 2, sourceId: "src_ema_sawp_2023", label: "EMA SAWP Minutes" },
    },
    { type: "text", value: " " },
    {
      type: "citation",
      value: "[3]",
      citationRef: { n: 3, sourceId: "src_ich_e6r3", label: "ICH E6(R3)" },
    },
    { type: "text", value: ". The DSMB charter must specify stopping rules, interim analysis triggers, and unblinding procedures " },
    {
      type: "citation",
      value: "[4]",
      citationRef: { n: 4, sourceId: "src_maple_sop_cl014", label: "MAP SOP-CL-014" },
    },
    { type: "text", value: ". Maple's internal SOP CL-014 requires stratification by baseline fibrosis stage and T2DM status, both of which the DSMB should review at interim analysis " },
    {
      type: "citation",
      value: "[4]",
      citationRef: { n: 4, sourceId: "src_maple_sop_cl014", label: "MAP SOP-CL-014" },
    },
    { type: "text", value: "." },
  ],
  passages: [
    {
      id: "pass_001",
      n: 1,
      authority: "FDA",
      kind: "Guidance",
      date: "Jul '24",
      score: 0.93,
      citedCount: 41,
      snippet:
        "The DSMB charter must specify stopping rules, interim analysis triggers, and unblinding procedures. For trials in populations with pre-existing hepatic conditions, DSMB oversight is strongly recommended regardless of phase.",
      sourceId: "src_fda_dsmb_2024",
      sourceTitle: "ICH E6(R3) — 15.18 Data Safety Monitoring Boards",
    },
    {
      id: "pass_002",
      n: 2,
      authority: "FDA",
      kind: "Guidance",
      date: "Nov '23",
      score: 0.71,
      citedCount: 13,
      snippet:
        "A DSMB should be established for trials enrolling vulnerable populations or where the intervention carries non-negligible safety risk. The charter must specify stopping rules, interim analysis triggers, and unblinding procedures.",
      sourceId: "src_fda_nash_2023",
      sourceTitle: "FDA – NASH Guidance — Endpoints for clinical trials in NASH",
    },
    {
      id: "pass_003",
      n: 3,
      authority: "EMA",
      kind: "Guidance",
      date: "Mar '23",
      score: 0.68,
      citedCount: 8,
      snippet:
        "Independent oversight via a DSMB or equivalent committee is expected for Phase II studies involving novel mechanisms with potential hepatic signals. Charter review by the SAWP is recommended prior to first enrolment.",
      sourceId: "src_ema_sawp_2023",
      sourceTitle: "EMA SAWP Scientific Advice — NASH Phase II Design Considerations",
    },
    {
      id: "pass_004",
      n: 4,
      authority: "Internal",
      kind: "SOP",
      date: "Jan '25",
      score: 0.61,
      citedCount: 3,
      snippet:
        "SOP CL-014: All Phase II oncology and metabolic trials must establish a DSMB with a charter approved by the Medical Director. Stratification factors (fibrosis stage, T2DM status) must be pre-specified and reviewed at each interim.",
      sourceId: "src_maple_sop_cl014",
      sourceTitle: "MAP SOP-CL-014 — DSMB Charter Requirements",
    },
  ],
};

export const SAMPLE_KB_INDEX_HEALTH: KbIndexHealth = {
  status: "synced",
  lastSyncedAgo: "14m ago",
  totalChunks: 482419,
  categories: [
    { label: "Regulators · FDA · EMA · MHRA", chunkCount: 142891 },
    { label: "ICH guidelines", chunkCount: 28485 },
    { label: "ClinicalTrials.gov + EU CTR", chunkCount: 158359 },
    { label: "PubMed (indexed abstracts)", chunkCount: 44128 },
    { label: "Internal · Maple SOPs", chunkCount: 7482 },
    { label: "Internal · Prior CSRs · CSP", chunkCount: 21195 },
  ],
  recentIngests: [
    {
      id: "ing_001",
      title: "ICH E6(R3) Step 4 adopted",
      authority: "ICH",
      chunksAdded: 312,
      age: "2d",
    },
    {
      id: "ing_002",
      title: "FDA draft guidance – DCT",
      authority: "FDA",
      chunksAdded: 98,
      age: "4d",
    },
    {
      id: "ing_003",
      title: "MAP-CRF-v2.1",
      authority: "Internal",
      chunksAdded: 44,
      age: "5d",
    },
    {
      id: "ing_004",
      title: "Pre-IND meeting minutes",
      authority: "Internal",
      chunksAdded: 27,
      age: "6d",
    },
  ],
  pinnedStudyCode: "MAP-204",
};

