export type { Role, OrgType, ProjectStatus, Organization, User, Project } from "@/types/project";
import type { InboxThread } from "@/types/inbox";
import type { KbAnswer, KbIndexHealth } from "@/types/knowledge";
import type { Organization, User, Project } from "@/types/project";
import type { ProtocolDocument } from "@/types/protocol";
import type { IntelData } from "@/types/intel";
import type { RegWritingDoc } from "@/types/writing";
import type { SafetyCase, SafetyNarrative, QueueCase, SafetySignal, CumulativeSafety } from "@/types/safety";
import type { EthicsApplication, FormSection, RequiredDoc, HraCheck, HraGap, RecMilestone, NihrPortfolio } from "@/types/ethics";

// Legacy aliases — kept while other pages migrate to @/types/*
export type MockOrganization = Organization;
export type MockUser = User;
export type MockProject = Project;

export const MOCK_ORG: Organization = {
  id: "org_maple_001",
  name: "Maple Therapeutics",
  type: "BIOTECH",
  dataResidency: "uk",
};

export const MOCK_USER: User = {
  id: "user_priya_001",
  name: "Priya Shah",
  email: "priya.shah@mapletherapeutics.com",
  role: "ra_lead",
  title: "Regulatory Affairs",
  initials: "PS",
  organizationId: MOCK_ORG.id,
};

// ── Projects ──────────────────────────────────────────────────────────────────

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj_map_204",
    code: "MAP-204",
    title: "Onaplazib in NASH",
    phase: "Phase II",
    indication: "Hepatology",
    regions: ["UK", "US", "DE"],
    status: "RECRUITING",
    targetEnrolment: 320,
    actualEnrolment: 198,
    siteCount: 28,
    openItems: 4,
    ownerId: "user_priya_001",
    ownerName: "Priya Shah",
    ownerInitials: "PS",
    ownerColor: "oklch(58% 0.10 185)",
    organizationId: "org_maple_001",
    startDate: "2023-03-01",
    endDate: "2026-06-01",
  },
  {
    id: "proj_map_117",
    code: "MAP-117",
    title: "Selvaxin combo, EGFRm NSCLC",
    phase: "Phase Ib",
    indication: "Oncology",
    regions: ["UK", "US"],
    status: "PRE_IND",
    targetEnrolment: 84,
    actualEnrolment: 0,
    siteCount: 6,
    openItems: 7,
    ownerId: "user_remi_001",
    ownerName: "Remi Okafor",
    ownerInitials: "RO",
    ownerColor: "oklch(55% 0.14 260)",
    organizationId: "org_maple_001",
    startDate: "2025-09-01",
    endDate: "2028-03-01",
  },
  {
    id: "proj_map_003",
    code: "MAP-003",
    title: "Paediatric AAV gene therapy",
    phase: "Phase III",
    indication: "Rare disease",
    regions: ["UK", "NL"],
    status: "IN_SCREENING",
    targetEnrolment: 24,
    actualEnrolment: 5,
    siteCount: 4,
    openItems: 2,
    ownerId: "user_marta_001",
    ownerName: "Marta Kovacs",
    ownerInitials: "MK",
    ownerColor: "oklch(62% 0.13 55)",
    organizationId: "org_maple_001",
    startDate: "2024-11-01",
    endDate: "2027-05-01",
  },
  {
    id: "proj_rap_089",
    code: "RAP-089",
    title: "TNFα blocker — psoriatic arthritis",
    phase: "Phase III",
    indication: "Immunology",
    regions: ["UK", "EU", "US", "CA"],
    status: "IN_FOLLOW_UP",
    targetEnrolment: 612,
    actualEnrolment: 575,
    siteCount: 61,
    openItems: 1,
    ownerId: "user_arjun_001",
    ownerName: "Arjun Patel",
    ownerInitials: "AP",
    ownerColor: "oklch(55% 0.14 210)",
    organizationId: "org_maple_001",
    startDate: "2021-06-01",
    endDate: "2026-09-01",
  },
  {
    id: "proj_rap_156",
    code: "RAP-156",
    title: "Cardiac biomarker dx study",
    phase: "Observational",
    indication: "Cardiovascular",
    regions: ["UK"],
    status: "RECRUITING",
    targetEnrolment: 1200,
    actualEnrolment: 576,
    siteCount: 14,
    openItems: 0,
    ownerId: "user_li_001",
    ownerName: "Li Tan",
    ownerInitials: "LT",
    ownerColor: "oklch(55% 0.12 145)",
    organizationId: "org_maple_001",
    startDate: "2024-01-01",
    endDate: "2027-01-01",
  },
  {
    id: "proj_map_301",
    code: "MAP-301",
    title: "Long COVID natural history",
    phase: "Observational",
    indication: "Infectious disease",
    regions: ["UK"],
    status: "REPORTING",
    targetEnrolment: 850,
    actualEnrolment: 850,
    siteCount: 22,
    openItems: 3,
    ownerId: "user_priya_001",
    ownerName: "Priya Shah",
    ownerInitials: "PS",
    ownerColor: "oklch(58% 0.10 185)",
    organizationId: "org_maple_001",
    startDate: "2022-01-01",
    endDate: "2025-12-01",
  },
  {
    id: "proj_map_811",
    code: "MAP-811",
    title: "Bispecific Ab — refractory AML",
    phase: "Phase I",
    indication: "Oncology",
    regions: ["UK", "DE"],
    status: "RECRUITING",
    targetEnrolment: 36,
    actualEnrolment: 30,
    siteCount: 5,
    openItems: 2,
    ownerId: "user_remi_001",
    ownerName: "Remi Okafor",
    ownerInitials: "RO",
    ownerColor: "oklch(55% 0.14 260)",
    organizationId: "org_maple_001",
    startDate: "2025-02-01",
    endDate: "2026-08-01",
  },
  {
    id: "proj_map_812",
    code: "MAP-812",
    title: "Bone marrow conditioning regimen",
    phase: "Phase II",
    indication: "Haematology",
    regions: ["UK"],
    status: "DRAFT",
    targetEnrolment: 90,
    actualEnrolment: 0,
    siteCount: 3,
    openItems: 5,
    ownerId: "user_marta_001",
    ownerName: "Marta Kovacs",
    ownerInitials: "MK",
    ownerColor: "oklch(62% 0.13 55)",
    organizationId: "org_maple_001",
    startDate: "2026-09-01",
    endDate: "2029-03-01",
  },
  {
    id: "proj_map_445",
    code: "MAP-445",
    title: "NASH fibrosis reversal study",
    phase: "Phase II",
    indication: "Hepatology",
    regions: ["UK", "US", "FR"],
    status: "RECRUITING",
    targetEnrolment: 200,
    actualEnrolment: 87,
    siteCount: 12,
    openItems: 0,
    ownerId: "user_priya_001",
    ownerName: "Priya Shah",
    ownerInitials: "PS",
    ownerColor: "oklch(58% 0.10 185)",
    organizationId: "org_maple_001",
    startDate: "2024-06-01",
    endDate: "2027-06-01",
  },
  {
    id: "proj_rap_290",
    code: "RAP-290",
    title: "PD-L1 inhibitor combo NSCLC",
    phase: "Phase II",
    indication: "Oncology",
    regions: ["UK", "US", "DE", "AU"],
    status: "IN_SCREENING",
    targetEnrolment: 450,
    actualEnrolment: 0,
    siteCount: 8,
    openItems: 3,
    ownerId: "user_arjun_001",
    ownerName: "Arjun Patel",
    ownerInitials: "AP",
    ownerColor: "oklch(55% 0.14 210)",
    organizationId: "org_maple_001",
    startDate: "2025-11-01",
    endDate: "2029-05-01",
  },
  {
    id: "proj_map_509",
    code: "MAP-509",
    title: "HER2+ breast cancer neoadjuvant",
    phase: "Phase II",
    indication: "Oncology",
    regions: ["UK", "EU"],
    status: "RECRUITING",
    targetEnrolment: 180,
    actualEnrolment: 142,
    siteCount: 19,
    openItems: 1,
    ownerId: "user_remi_001",
    ownerName: "Remi Okafor",
    ownerInitials: "RO",
    ownerColor: "oklch(55% 0.14 260)",
    organizationId: "org_maple_001",
    startDate: "2023-08-01",
    endDate: "2026-02-01",
  },
  {
    id: "proj_rap_044",
    code: "RAP-044",
    title: "Omega-3 cardiovascular protection",
    phase: "Phase III",
    indication: "Cardiovascular",
    regions: ["UK", "US"],
    status: "IN_FOLLOW_UP",
    targetEnrolment: 3500,
    actualEnrolment: 3240,
    siteCount: 45,
    openItems: 0,
    ownerId: "user_li_001",
    ownerName: "Li Tan",
    ownerInitials: "LT",
    ownerColor: "oklch(55% 0.12 145)",
    organizationId: "org_maple_001",
    startDate: "2020-04-01",
    endDate: "2026-10-01",
  },
  {
    id: "proj_map_712",
    code: "MAP-712",
    title: "CRISPR sickle-cell correction",
    phase: "Phase I",
    indication: "Haematology",
    regions: ["UK"],
    status: "DRAFT",
    targetEnrolment: 30,
    actualEnrolment: 0,
    siteCount: 2,
    openItems: 8,
    ownerId: "user_marta_001",
    ownerName: "Marta Kovacs",
    ownerInitials: "MK",
    ownerColor: "oklch(62% 0.13 55)",
    organizationId: "org_maple_001",
    startDate: "2027-01-01",
    endDate: "2029-12-01",
  },
  {
    id: "proj_rap_221",
    code: "RAP-221",
    title: "Anti-IL-17 in plaque psoriasis",
    phase: "Phase III",
    indication: "Dermatology",
    regions: ["UK", "EU", "US"],
    status: "COMPLETED",
    targetEnrolment: 612,
    actualEnrolment: 612,
    siteCount: 38,
    openItems: 0,
    ownerId: "user_arjun_001",
    ownerName: "Arjun Patel",
    ownerInitials: "AP",
    ownerColor: "oklch(55% 0.14 210)",
    organizationId: "org_maple_001",
    startDate: "2019-06-01",
    endDate: "2024-12-01",
  },
];

// ── Inbox ──────────────────────────────────────────────────────────────────────

export const MOCK_INBOX_THREADS: InboxThread[] = [
  {
    id: "thread_001",
    kind: "review",
    sender: "R. Okafor",
    senderInitials: "RO",
    senderColor: "oklch(55% 0.14 260)",
    subject: "Protocol v3 ready for your review — MAP-117",
    snippet: "Hi Priya, I've completed the Phase Ib dose-escalation section and flagged the MHRA CTA points for your sign-off…",
    domainTag: "Protocol",
    studyCode: "MAP-117",
    urgency: "urgent",
    age: "12 min",
    isUnread: true,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_001a",
        from: "Remi Okafor",
        fromInitials: "RO",
        fromColor: "oklch(55% 0.14 260)",
        body: "Hi Priya,\n\nI've completed the Phase Ib dose-escalation section for MAP-117 (Selvaxin combo, EGFRm NSCLC) and uploaded Protocol v3. The AI flagged two potential ICH E6(R3) gaps in Section 4.2 — specifically around the stopping rules for DLT Grade ≥3. I've annotated these with citations from FDA guidance but I'd appreciate your sign-off before we submit the CTA to MHRA.\n\nI've also drafted the eligibility exclusion criteria based on the prior Phase Ia data — please review criterion 7 (prior EGFR TKI therapy) as the confidence score is 62%, just above the threshold.\n\nCould you review and approve by EOD Thursday? The MHRA pre-submission slot is Friday 09:00.",
        age: "12 min",
      },
    ],
  },
  {
    id: "thread_002",
    kind: "regulator",
    sender: "MHRA · ILAP",
    senderInitials: "MH",
    subject: "ILAP target development profile — MAP-204 Type II variation",
    snippet: "Your Innovative Licensing and Access Pathway application for MAP-204 has been assigned to a product specialist. Next steps: submit updated TDP by 4 July…",
    domainTag: "Regulator",
    studyCode: "MAP-204",
    urgency: "high",
    age: "1h",
    isUnread: true,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_002a",
        from: "MHRA · ILAP Team",
        fromInitials: "MH",
        body: "Dear Maple Therapeutics,\n\nYour Innovative Licensing and Access Pathway (ILAP) application for MAP-204 (Onaplazib, NASH) has been reviewed by the MHRA and assigned to a designated product specialist.\n\nRequired action: Please submit an updated Target Development Profile (TDP) reflecting the Phase II interim data (data cut: 31 May 2026) no later than 4 July 2026. The updated TDP should address the hepatic safety signal raised at the last Coordination Group meeting.\n\nA Scientific Advice meeting has been provisionally booked for 18 July 2026. Dial-in details will follow separately.\n\nPlease confirm receipt of this communication within 5 working days.",
        age: "1h",
      },
    ],
  },
  {
    id: "thread_003",
    kind: "mention",
    sender: "L. Tan",
    senderInitials: "LT",
    senderColor: "oklch(55% 0.12 145)",
    subject: "@Priya — eligibility query on RAP-156 cardiac biomarker criteria",
    snippet: "@Priya, I've flagged criterion 4 (eGFR threshold) against the 2025 NICE guidance update. The AI confidence is 71% — below your usual threshold. Can you review?",
    domainTag: "Eligibility",
    studyCode: "RAP-156",
    urgency: "normal",
    age: "2h",
    isUnread: true,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_003a",
        from: "Li Tan",
        fromInitials: "LT",
        fromColor: "oklch(55% 0.12 145)",
        body: "@Priya\n\nQuick query on the RAP-156 inclusion criterion 4 (eGFR ≥45 mL/min/1.73m²). The AI has cross-referenced this against the 2025 NICE CG182 update and flagged a potential discrepancy — the updated guidance recommends ≥50 for the cardiac biomarker population we're targeting, particularly in patients with concurrent ACE inhibitor use.\n\nConfidence on this criterion is 71% — below the 85% green threshold. I've attached the relevant NICE passage and the prior MAP-156 precedent.\n\nShould we revise criterion 4 before the next site initiation visit on 30 June?",
        age: "2h",
      },
    ],
  },
  {
    id: "thread_004",
    kind: "safety_flag",
    sender: "AI · Cohortly",
    senderInitials: "AI",
    subject: "Safety flag — SAE cluster detected, MAP-204 hepatic events",
    snippet: "Automated signal detection has identified a potential cluster of Grade 2+ hepatic AEs (n=4, 28 days). PRR 3.2, χ² 8.1. Enhanced review recommended…",
    domainTag: "Safety",
    studyCode: "MAP-204",
    urgency: "urgent",
    age: "3h",
    isUnread: true,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_004a",
        from: "AI · Cohortly",
        fromInitials: "AI",
        body: "Automated safety signal detection has identified a potential cluster of Grade 2 or higher hepatic adverse events in MAP-204 (Onaplazib, NASH) over a rolling 28-day window.\n\nSignal summary:\n• Events: 4 Grade 2+ hepatic AEs (ALT/AST elevation)\n• Proportional Reporting Ratio (PRR): 3.2 (threshold: 2.0)\n• χ² statistic: 8.1 (threshold: 4.0)\n• MedDRA PT: Drug-induced liver injury (10072268)\n\nThis signal exceeds the pre-defined pharmacovigilance thresholds configured for MAP-204. Under the MAP-204 Risk Management Plan (v2.1), a hepatic safety monitoring review is required within 5 working days.\n\nRecommended actions: (1) Review individual SAE narratives for the 4 subjects. (2) Assess against the DSMB charter stopping rules. (3) Notify the Principal Investigator at UCL site.\n\nThis flag has been added to the Safety & PV queue. Confidence: 0.89 · Model: cohortly-safety-v2 · Retrieved from: MAP-204 RMP v2.1, ICH E2A.",
        age: "3h",
      },
    ],
  },
  {
    id: "thread_005",
    kind: "regulator",
    sender: "HRA · REC",
    senderInitials: "HR",
    subject: "REC opinion issued — MAP-003 paediatric amendment 3",
    snippet: "The Research Ethics Committee has issued a Favourable Opinion for Amendment 3 to MAP-003. One condition attached: revised PIS (plain English summary) required within 28 days…",
    domainTag: "Ethics",
    studyCode: "MAP-003",
    urgency: "high",
    age: "4h",
    isUnread: false,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_005a",
        from: "HRA · South Central — Oxford C REC",
        fromInitials: "HR",
        body: "Dear Chief Investigator,\n\nThe Research Ethics Committee has reviewed Amendment 3 to MAP-003 (Paediatric AAV gene therapy) at its meeting on 19 June 2026 and has issued a Favourable Opinion.\n\nCondition: The Committee requests a revised Patient Information Sheet (PIS) and Assent Form for the 8–11 age group. The current readability score (Flesch-Kincaid Grade 7.2) exceeds the recommended maximum of Grade 6 for this age group. Please resubmit the revised PIS within 28 days.\n\nThe Favourable Opinion reference is: 26/SC/0142/AM03. Please quote this on all correspondence.\n\nYou may proceed with the amendment in line with your response once the condition is satisfied.",
        age: "4h",
      },
    ],
  },
  {
    id: "thread_006",
    kind: "regulator",
    sender: "FDA · CDER",
    senderInitials: "FD",
    subject: "IND 149-228 — Information Request re: MAP-204 hepatic safety data",
    snippet: "Reference your IND 149-228. CDER requests additional hepatic histopathology data from the 12-week preclinical study (Study RD-2024-07) within 30 days…",
    domainTag: "Regulator",
    studyCode: "MAP-204",
    urgency: "urgent",
    age: "Yesterday",
    isUnread: false,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_006a",
        from: "FDA · CDER Division of Hepatology",
        fromInitials: "FD",
        body: "RE: IND 149-228, Onaplazib (MAP-204), Information Request\n\nDear Sponsor,\n\nDuring its review of your IND Annual Report (submitted 1 June 2026), the Division identified the need for additional data to complete its assessment of the hepatic safety profile of Onaplazib.\n\nSpecifically, CDER requests:\n1. Full hepatic histopathology tables from the 12-week rat repeat-dose study (Study RD-2024-07), including individual animal data.\n2. Bridging analysis comparing preclinical ALT/AST elevations to the clinical Grade 2+ events reported in the Phase II interim.\n3. Proposed hepatic monitoring algorithm for the remainder of the Phase II study.\n\nThis information must be submitted within 30 days of the date of this letter (by 23 July 2026). Failure to respond may result in a clinical hold.",
        age: "Yesterday",
      },
    ],
  },
  {
    id: "thread_007",
    kind: "review",
    sender: "M. Kovacs",
    senderInitials: "MK",
    senderColor: "oklch(62% 0.13 55)",
    subject: "IRAS amendment 3 ready for QA sign-off — MAP-003",
    snippet: "Marta Kovacs assigned you as QA reviewer on IRAS amendment 3 for MAP-003. Completion 94%, 1 section flagged for manual review (Section E, gene therapy-specific questions)…",
    domainTag: "Ethics",
    studyCode: "MAP-003",
    urgency: "normal",
    age: "2d",
    isUnread: false,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_007a",
        from: "Marta Kovacs",
        fromInitials: "MK",
        fromColor: "oklch(62% 0.13 55)",
        body: "Hi Priya,\n\nI've assigned you as QA reviewer on IRAS Amendment 3 for MAP-003. The AI has auto-populated 94% of the form using the approved protocol and the REC correspondence. One section needs manual review:\n\n• Section E (Advanced Therapy Medicinal Products) — the AAV serotype-specific questions (E7–E9) require manual input as these aren't covered in the KB yet. I've drafted placeholder answers but confidence scores are 41–55%, well below threshold.\n\nEverything else (Sections A–D, F–H) is complete with confidence ≥82%. The application is otherwise ready for submission pending your sign-off on Section E.\n\nCan you review by end of play Friday?",
        age: "2d",
      },
    ],
  },
  {
    id: "thread_008",
    kind: "mention",
    sender: "A. Patel",
    senderInitials: "AP",
    senderColor: "oklch(55% 0.14 210)",
    subject: "@Priya — RAP-089 CTD 2.7.4 summary needs your input",
    snippet: "@Priya could you review the immunogenicity section of the RAP-089 CTD 2.7.4 clinical summary? The AI draft has 3 unverified citations from the EMA CHMP assessment report…",
    domainTag: "Reg Writing",
    studyCode: "RAP-089",
    urgency: "normal",
    age: "3d",
    isUnread: false,
    organizationId: "org_maple_001",
    messages: [
      {
        id: "msg_008a",
        from: "Arjun Patel",
        fromInitials: "AP",
        fromColor: "oklch(55% 0.14 210)",
        body: "@Priya\n\nThe AI-drafted immunogenicity section (CTD 2.7.4.3) for RAP-089 has 3 citations flagged as unverified — they reference the EMA CHMP Assessment Report for the reference biologic (adalimumab), but the KB doesn't have the full PDF indexed yet (only the public summary). The citation confidence on those 3 statements is 48–55%.\n\nI've highlighted the passages in the document. Options: (1) We pause and get the CHMP full report indexed (2–3 days), (2) I manually verify and annotate them, (3) we rephrase to cite the public summary only.\n\nWhat's your preference? The EMA submission window is 15 July.",
        age: "3d",
      },
    ],
  },
];

// ── Knowledge Base ─────────────────────────────────────────────────────────────

export const SAMPLE_KB_ANSWER: KbAnswer = {
  query: "When is a DSMB required for a Phase II NASH trial in the UK?",
  confidence: 92,
  sourceCount: 4,
  latencyMs: 730,
  modelVersion: "cohort-v3",
  segments: [
    { type: "text", value: "A DSMB is " },
    { type: "text", value: "required" },
    { type: "text", value: " for Phase II NASH trials in the UK when the trial enrolls vulnerable populations or where the intervention carries non-negligible safety risk " },
    {
      type: "citation",
      value: "[1]",
      citationRef: { n: 1, sourceId: "src_fda_dsmb_2024", label: "FDA DSMB Guidance" },
    },
    { type: "text", value: ". For NASH specifically, the FDA's 2023 guidance and EMA's SAWP minutes recommend independent safety oversight given the hepatic toxicity considerations " },
    {
      type: "citation",
      value: "[2]",
      citationRef: { n: 2, sourceId: "src_ema_sawp_2023", label: "EMA SAWP Minutes" },
    },
    { type: "text", value: " " },
    {
      type: "citation",
      value: "[3]",
      citationRef: { n: 3, sourceId: "src_ich_e6r3", label: "ICH E6(R3)" },
    },
    { type: "text", value: ". The DSMB charter must specify stopping rules, interim analysis triggers, and unblinding procedures " },
    {
      type: "citation",
      value: "[4]",
      citationRef: { n: 4, sourceId: "src_maple_sop_cl014", label: "MAP SOP-CL-014" },
    },
    { type: "text", value: ". Maple's internal SOP CL-014 requires stratification by baseline fibrosis stage and T2DM status, both of which the DSMB should review at interim analysis " },
    {
      type: "citation",
      value: "[4]",
      citationRef: { n: 4, sourceId: "src_maple_sop_cl014", label: "MAP SOP-CL-014" },
    },
    { type: "text", value: "." },
  ],
  passages: [
    {
      id: "pass_001",
      n: 1,
      authority: "FDA",
      kind: "Guidance",
      date: "Jul '24",
      score: 0.93,
      citedCount: 41,
      snippet:
        "The DSMB charter must specify stopping rules, interim analysis triggers, and unblinding procedures. For trials in populations with pre-existing hepatic conditions, DSMB oversight is strongly recommended regardless of phase.",
      sourceId: "src_fda_dsmb_2024",
      sourceTitle: "ICH E6(R3) — 15.18 Data Safety Monitoring Boards",
    },
    {
      id: "pass_002",
      n: 2,
      authority: "FDA",
      kind: "Guidance",
      date: "Nov '23",
      score: 0.71,
      citedCount: 13,
      snippet:
        "A DSMB should be established for trials enrolling vulnerable populations or where the intervention carries non-negligible safety risk. The charter must specify stopping rules, interim analysis triggers, and unblinding procedures.",
      sourceId: "src_fda_nash_2023",
      sourceTitle: "FDA – NASH Guidance — Endpoints for clinical trials in NASH",
    },
    {
      id: "pass_003",
      n: 3,
      authority: "EMA",
      kind: "Guidance",
      date: "Mar '23",
      score: 0.68,
      citedCount: 8,
      snippet:
        "Independent oversight via a DSMB or equivalent committee is expected for Phase II studies involving novel mechanisms with potential hepatic signals. Charter review by the SAWP is recommended prior to first enrolment.",
      sourceId: "src_ema_sawp_2023",
      sourceTitle: "EMA SAWP Scientific Advice — NASH Phase II Design Considerations",
    },
    {
      id: "pass_004",
      n: 4,
      authority: "Internal",
      kind: "SOP",
      date: "Jan '25",
      score: 0.61,
      citedCount: 3,
      snippet:
        "SOP CL-014: All Phase II oncology and metabolic trials must establish a DSMB with a charter approved by the Medical Director. Stratification factors (fibrosis stage, T2DM status) must be pre-specified and reviewed at each interim.",
      sourceId: "src_maple_sop_cl014",
      sourceTitle: "MAP SOP-CL-014 — DSMB Charter Requirements",
    },
  ],
};

// ── Protocol Copilot (S07) ───────────────────────────────────────────────────

const STUDY_DESIGN_CONTENT = {
  type: "doc",
  content: [
    {
      type: "paragraph",
      content: [
        {
          type: "text",
          text: "Multicenter, randomised, double-blind, placebo-controlled adaptive Phase II study evaluating onaplazib 30 mg and 60 mg QD in adults with biopsy-confirmed NASH (F2-F3). ",
        },
        { type: "citation", attrs: { n: 14, label: "FDA·Adaptive Designs", sourceId: "src_fda_adaptive" } },
        { type: "text", text: " " },
        { type: "citation", attrs: { n: 3, label: "MAP-204 IB", sourceId: "src_map204_ib" } },
        { type: "text", text: " " },
        { type: "citation", attrs: { n: 1, label: "ICH E6(R3) §5.18", sourceId: "src_ich_e6" } },
      ],
    },
    {
      type: "paragraph",
      content: [
        { type: "text", text: "The study employs " },
        { type: "text", marks: [{ type: "bold" }], text: "a two-stage adaptive design" },
        {
          type: "text",
          text: " with a pre-specified interim analysis at 50% of target enrolment to support a futility stop at the interim. Subjects will be randomised 1:1:1 to receive onaplazib 30 mg, onaplazib 60 mg or matched placebo administered orally once daily for 52 weeks.",
        },
      ],
    },
    {
      type: "paragraph",
      content: [
        {
          type: "text",
          text: "Stratification factors include baseline NAS score (≥2 vs ≥5), presence of type 2 diabetes mellitus, and recruiting region (UK · EU · US). ",
        },
        { type: "citation", attrs: { n: 43, label: "NASH CRN strat.", sourceId: "src_nash_crn" } },
      ],
    },
    {
      type: "paragraph",
      content: [
        { type: "text", text: "The primary endpoint is the proportion of subjects achieving a " },
        {
          type: "text",
          marks: [{ type: "bold" }],
          text: "≥2-point reduction in NAS score without worsening of fibrosis at Week 52",
        },
        { type: "text", text: ", assessed by central blinded histopathology review. " },
        { type: "citation", attrs: { n: 7, label: "FDA NASH Guidance", sourceId: "src_fda_nash" } },
        {
          type: "text",
          text: " Secondary endpoints include change in liver stiffness (MRE), MRI-PDFF, ALT/AST normalisation, and HOMA-IR. ",
        },
        { type: "citation", attrs: { n: 2, label: "EMA·NASH reflection", sourceId: "src_ema_nash" } },
      ],
    },
    {
      type: "paragraph",
      content: [
        {
          type: "text",
          text: "A pre-specified DSMB will conduct unblinded safety reviews every 12 weeks following first dosing. ",
        },
        { type: "citation", attrs: { n: 11, label: "ICH E6(R3) §5.5", sourceId: "src_ich_dsmb" } },
        { type: "text", text: " Stopping rules are defined in Section 8.4." },
      ],
    },
  ],
};

export const MOCK_PROTOCOL_DOC: ProtocolDocument = {
  id: "doc_map204_protocol_v3",
  projectId: "proj_map_204",
  projectCode: "MAP-204",
  projectTitle: "Onaplazib in NASH",
  status: "DRAFT",
  lastEditedBy: "Priya",
  lastEditedAgo: "14 minutes ago",
  therapeuticArea: "NASH",
  phase: "Phase II",
  complianceMeters: [
    { framework: "SPIRIT", completed: 32, total: 33 },
    { framework: "ICH E6(R3)", completed: 27, total: 28 },
    { framework: "MHRA CTA", completed: 14, total: 18 },
    { framework: "HRA REC", completed: 9, total: 12 },
  ],
  sections: [
    { id: "sec_01", number: "1", heading: "Synopsis", sourceCount: 1, flaggedCount: 0, gapCount: 0, status: "complete", contentJson: { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: "Summary of the MAP-204 Phase II onaplazib study in NASH." }] }] }, complianceScore: 100 },
    { id: "sec_02", number: "2", heading: "Background & rationale", sourceCount: 3, flaggedCount: 1, gapCount: 0, status: "flagged", contentJson: { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: "NASH affects an estimated 20% of the adult population in Western countries…" }] }] }, complianceScore: 87 },
    { id: "sec_03", number: "3", heading: "Objectives & endpoints", sourceCount: 2, flaggedCount: 0, gapCount: 0, status: "complete", contentJson: { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: "Primary objective: demonstrate superiority of onaplazib over placebo on the composite histological endpoint at Week 52." }] }] }, complianceScore: 95 },
    { id: "sec_04", number: "4", heading: "Study design & schema", sourceCount: 7, flaggedCount: 2, gapCount: 1, status: "draft", contentJson: STUDY_DESIGN_CONTENT, complianceScore: 78 },
    { id: "sec_05", number: "5", heading: "Eligibility", sourceCount: 4, flaggedCount: 1, gapCount: 0, status: "draft", contentJson: { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: "Inclusion: adults 18–75 years with biopsy-confirmed NASH NAS ≥4…" }] }] }, complianceScore: 82 },
    { id: "sec_06", number: "6", heading: "Treatments", sourceCount: 2, flaggedCount: 0, gapCount: 0, status: "complete", contentJson: { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: "Onaplazib 30 mg and 60 mg QD oral tablet; matched placebo." }] }] }, complianceScore: 91 },
    { id: "sec_07", number: "7", heading: "Efficacy assessments", sourceCount: 3, flaggedCount: 0, gapCount: 0, status: "draft", contentJson: { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: "Liver biopsy at Baseline and Week 52 assessed by NASH CRN scoring system." }] }] }, complianceScore: 70 },
    { id: "sec_08", number: "8", heading: "Safety assessments", sourceCount: 2, flaggedCount: 1, gapCount: 0, status: "flagged", contentJson: { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: "Safety monitoring includes hepatic function panels every 4 weeks." }] }] }, complianceScore: 74 },
    { id: "sec_09", number: "9", heading: "Statistical plan", sourceCount: 4, flaggedCount: 0, gapCount: 1, status: "draft", contentJson: { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: "Sample size: 320 subjects (80% power, α=0.05, 2-sided)." }] }] }, complianceScore: 65 },
    { id: "sec_10", number: "10", heading: "Operational procedures", sourceCount: 1, flaggedCount: 0, gapCount: 0, status: "empty", contentJson: { type: "doc", content: [{ type: "paragraph", content: [] }] }, complianceScore: 0 },
  ],
  retrievedSources: [
    { id: "src_fda_adaptive", n: 14, authority: "FDA", title: "Adaptive Designs for Clinical Trials of Drugs and Biologics", relevanceScore: 93, kind: "Guidance", snippet: "Adaptive designs allow for pre-specified modifications based on accumulated data without undermining trial validity or integrity…" },
    { id: "src_map204_ib", n: 3, authority: "Sponsor", title: "MAP-204 Investigator's Brochure v4", relevanceScore: 91, kind: "Protocol", snippet: "Non-clinical and clinical data supporting the rationale for onaplazib in NASH, including Phase I safety and PK summary…" },
    { id: "src_ema_sawp", n: 9, authority: "EMA", title: "EMA·SAWP reflection paper — adaptive designs", relevanceScore: 88, kind: "Guideline", snippet: "Scientific considerations for adaptive designs with confirmatory intent under EMA regulatory framework…" },
    { id: "src_fda_nash", n: 7, authority: "FDA", title: "FDA Guidance for Industry — NASH: Developing Drugs", relevanceScore: 85, kind: "Guidance", snippet: "Histological endpoints (NAS score improvement ≥2 points without fibrosis worsening) are acceptable as primary endpoints for NASH trials…" },
    { id: "src_spirit_2013", n: 22, authority: "SPIRIT", title: "SPIRIT 2013: Standard Protocol Items", relevanceScore: 84, kind: "Guideline", snippet: "Recommendations for content of clinical trial protocols and the associated explanatory document…" },
    { id: "src_map204_ib_v4", n: 3, authority: "Sponsor", title: "MAP-204 IB v4", relevanceScore: 91, kind: "Protocol", snippet: "Investigator brochure version 4 incorporating Phase Ib interim data…" },
    { id: "src_ich_e6", n: 1, authority: "ICH", title: "ICH E6(R3) — Good Clinical Practice", relevanceScore: 96, kind: "Guideline", snippet: "§5.18 Investigational product accountability and §5.5 DSMB requirements under GCP…" },
    { id: "src_ich_dsmb", n: 11, authority: "ICH", title: "ICH E6(R3) §5.5 — DSMB", relevanceScore: 90, kind: "Guideline", snippet: "Data Safety Monitoring Board charter requirements and interim analysis procedures…" },
    { id: "src_nash_crn", n: 43, authority: "Internal", title: "NASH CRN Stratification Reference", relevanceScore: 79, kind: "SOP", snippet: "Stratification factors for randomisation per NASH CRN scoring conventions…" },
    { id: "src_ema_nash", n: 2, authority: "EMA", title: "EMA — NASH reflection paper", relevanceScore: 83, kind: "Guideline", snippet: "Secondary endpoints and MRI-based biomarkers acceptable for NASH trials…" },
  ],
  recommendation: {
    id: "rec_futility_stop",
    tag: "adaptive",
    status: "confirmed",
    text: "Consider adding a futility stop at the interim. In 23 of 27 precedent NASH trials with similar endpoints, futility rules were specified and accepted by FDA at IND review.",
    confidence: 91,
    precedentCount: 27,
    sectionId: "sec_04",
  },
  taEvidence: {
    precedentProtocols: 27,
    similarTrials: 22,
    sponsors: ["FDA", "EMA", "Gilead", "Madrigal"],
    confidence: 93,
    recruitment: 50,
  },
};

// ── Eligibility Engine (S08) ──────────────────────────────────────────────────

export const MOCK_ELIGIBILITY_MAP204 = {
  projectId: "proj_map_204",
  projectCode: "MAP-204",
  projectTitle: "Onaplazib in NASH",
  indication: "NASH",
  summary: {
    poolPct: 23.4,
    poolLabel: "Tight",
    screenFailurePct: 38,
    screenFailureBenchmarkLow: 31,
    screenFailureBenchmarkHigh: 44,
    timeToEnrolMonths: 14.2,
    timeToEnrolDelta: -2.1,
    comparatorTrials: [
      { nct: "NCT04990908", sponsor: "Madrigal", pct: 18 },
      { nct: "NCT05020496", sponsor: "Gilead", pct: 22 },
      { nct: "NCT05096715", sponsor: "Novo Nordisk", pct: 31 },
    ],
    dataAsOf: "2026-06-01",
  },
  criteria: [
    {
      id: "I1",
      kind: "INCLUSION",
      text: "Age 18–75 years at time of screening",
      feasibility: 94,
      source: "Precedent",
      regMandated: false,
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "I2",
      kind: "INCLUSION",
      text: "Biopsy-confirmed NASH with NAS ≥4 (steatosis ≥1, lobular inflammation ≥1, hepatocellular ballooning ≥1) within 6 months of screening",
      feasibility: 71,
      source: "FDA mandate",
      regMandated: true,
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "I3",
      kind: "INCLUSION",
      text: "Fibrosis stage F2 or F3 per Kleiner scoring system on screening biopsy",
      feasibility: 54,
      source: "EMA SAWP",
      regMandated: true,
      warning: "Narrows pool by 14.2% beyond precedent median — consider relaxing to include F1–F3",
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "I4",
      kind: "INCLUSION",
      text: "ALT ≤5× ULN at screening",
      feasibility: 82,
      source: "Precedent",
      regMandated: false,
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "I5",
      kind: "INCLUSION",
      text: "BMI ≥27 kg/m² at screening",
      feasibility: 78,
      source: "AASLD",
      regMandated: false,
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "I6",
      kind: "INCLUSION",
      text: "Able to provide written informed consent and comply with all study procedures",
      feasibility: 98,
      source: "Sponsor SOP",
      regMandated: true,
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "I7",
      kind: "INCLUSION",
      text: "Willing to undergo repeat liver biopsy at Week 52 for primary endpoint assessment",
      feasibility: 61,
      source: "FDA mandate",
      regMandated: false,
      warning: "Inconsistent across sites — 4 sites report patient refusal rate >30%",
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "I8",
      kind: "INCLUSION",
      text: "Stable concomitant medications for ≥3 months prior to screening biopsy",
      feasibility: 87,
      source: "Precedent",
      regMandated: false,
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "E1",
      kind: "EXCLUSION",
      text: "Active or recent (< 12 months) alcohol consumption >14 units/week (female) or >21 units/week (male)",
      feasibility: 81,
      source: "Precedent",
      regMandated: false,
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "E2",
      kind: "EXCLUSION",
      text: "Type 1 diabetes mellitus or poorly controlled Type 2 DM (HbA1c >9.5% at screening)",
      feasibility: 72,
      source: "AASLD",
      regMandated: true,
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "E3",
      kind: "EXCLUSION",
      text: "Prior bariatric surgery or planned major surgical intervention during study period",
      feasibility: 91,
      source: "Precedent",
      regMandated: false,
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "E4",
      kind: "EXCLUSION",
      text: "Decompensated cirrhosis (Child-Pugh class B or C) or prior hepatic decompensation event",
      feasibility: 76,
      source: "FDA mandate",
      regMandated: true,
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "E5",
      kind: "EXCLUSION",
      text: "Confirmed active hepatitis B (HBsAg+) or hepatitis C (HCV RNA+) infection",
      feasibility: 83,
      source: "EMA SAWP",
      regMandated: true,
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
    {
      id: "E6",
      kind: "EXCLUSION",
      text: "Uncorrected thyroid dysfunction (TSH <0.3 or >5.0 mIU/L) without stable hormone replacement therapy",
      feasibility: 88,
      source: "Sponsor SOP",
      regMandated: false,
      warning: "Narrows pool by 8.1% — consider limiting exclusion to untreated dysfunction only",
      projectId: "proj_map_204",
      organizationId: "org_maple_001",
    },
  ],
  levers: [
    {
      id: "lev_01",
      label: "Relax I3 to F1–F3",
      description: "Expand fibrosis stage eligibility to include F1",
      delta: 5.2,
      enabled: false,
    },
    {
      id: "lev_02",
      label: "Allow MRE at Wk 52",
      description: "Accept imaging-based assessment in place of biopsy for I7",
      delta: 3.2,
      enabled: false,
    },
    {
      id: "lev_03",
      label: "Relax BMI to ≥23",
      description: "Lower BMI threshold in I5 from ≥27 to ≥23 kg/m²",
      delta: 2.1,
      enabled: false,
    },
    {
      id: "lev_04",
      label: "Relax E2 to HbA1c ≤10%",
      description: "Widen poorly controlled T2DM exclusion threshold",
      delta: 1.8,
      enabled: false,
    },
  ],
  demographics: [
    { group: "Female", modelled: 38, fdaTarget: 50 },
    { group: "Black / African", modelled: 8, fdaTarget: 12 },
    { group: "South Asian", modelled: 11, fdaTarget: 10 },
    { group: "Hispanic", modelled: 9, fdaTarget: 14 },
    { group: "Age 65+", modelled: 15, fdaTarget: 20 },
  ],
  sites: [
    { id: "site_001", name: "UCL Liver Centre", city: "London", readiness: 92 },
    { id: "site_002", name: "King's College Hospital", city: "London", readiness: 87 },
    { id: "site_003", name: "University of Edinburgh", city: "Edinburgh", readiness: 81 },
    { id: "site_004", name: "Manchester Royal Infirmary", city: "Manchester", readiness: 74 },
    { id: "site_005", name: "Queen Elizabeth Hospital", city: "Birmingham", readiness: 68 },
  ],
};

export const SAMPLE_KB_INDEX_HEALTH: KbIndexHealth = {
  status: "synced",
  lastSyncedAgo: "14m ago",
  totalChunks: 482419,
  categories: [
    { label: "Regulators · FDA · EMA · MHRA", chunkCount: 142891 },
    { label: "ICH guidelines", chunkCount: 28485 },
    { label: "ClinicalTrials.gov + EU CTR", chunkCount: 158359 },
    { label: "PubMed (indexed abstracts)", chunkCount: 44128 },
    { label: "Internal · Maple SOPs", chunkCount: 7482 },
    { label: "Internal · Prior CSRs · CSP", chunkCount: 21195 },
  ],
  recentIngests: [
    {
      id: "ing_001",
      title: "ICH E6(R3) Step 4 adopted",
      authority: "ICH",
      chunksAdded: 312,
      age: "2d",
    },
    {
      id: "ing_002",
      title: "FDA draft guidance – DCT",
      authority: "FDA",
      chunksAdded: 98,
      age: "4d",
    },
    {
      id: "ing_003",
      title: "MAP-CRF-v2.1",
      authority: "Internal",
      chunksAdded: 44,
      age: "5d",
    },
    {
      id: "ing_004",
      title: "Pre-IND meeting minutes",
      authority: "Internal",
      chunksAdded: 27,
      age: "6d",
    },
  ],
  pinnedStudyCode: "MAP-204",
};

// ── Feasibility Simulator ─────────────────────────────────────────────────────

export const MOCK_FEASIBILITY_MAP204 = {
  projectId: "proj_map_204",
  projectCode: "MAP-204",
  projectTitle: "Onaplazib in NASH",
  indication: "NASH",
  kpis: {
    timeToN: 14.2,
    timeToNDelta: -1.8,
    eligiblePoolPct: 23.4,
    eligiblePoolLabel: "Tight",
    activationCostGbp: 2100000,
    activationCostDelta: -180000,
    probabilityOfSuccessPct: 68,
    probabilityOfSuccessDelta: 4,
    criticalPathDays: 512,
    criticalPathDelta: -22,
    criticalPathLabel: "IND → DBL",
    targetN: 320,
  },
  forecast: [
    { month: 0,  p10: 0,   p50: 0,   p90: 0,   ciLow: 0,   ciHigh: 0,   sponsorPlan: 0,   target: 0 },
    { month: 1,  p10: 4,   p50: 8,   p90: 12,  ciLow: 3,   ciHigh: 14,  sponsorPlan: 10,  target: 10 },
    { month: 2,  p10: 10,  p50: 18,  p90: 27,  ciLow: 8,   ciHigh: 30,  sponsorPlan: 22,  target: 22 },
    { month: 3,  p10: 18,  p50: 30,  p90: 44,  ciLow: 15,  ciHigh: 48,  sponsorPlan: 36,  target: 36 },
    { month: 4,  p10: 27,  p50: 44,  p90: 63,  ciLow: 23,  ciHigh: 68,  sponsorPlan: 51,  target: 53 },
    { month: 5,  p10: 37,  p50: 59,  p90: 83,  ciLow: 32,  ciHigh: 89,  sponsorPlan: 67,  target: 70 },
    { month: 6,  p10: 48,  p50: 75,  p90: 105, ciLow: 42,  ciHigh: 112, sponsorPlan: 83,  target: 88 },
    { month: 7,  p10: 60,  p50: 92,  p90: 128, ciLow: 53,  ciHigh: 136, sponsorPlan: 100, target: 106 },
    { month: 8,  p10: 73,  p50: 110, p90: 152, ciLow: 65,  ciHigh: 161, sponsorPlan: 118, target: 125 },
    { month: 9,  p10: 87,  p50: 129, p90: 177, ciLow: 79,  ciHigh: 187, sponsorPlan: 136, target: 145 },
    { month: 10, p10: 102, p50: 149, p90: 203, ciLow: 93,  ciHigh: 214, sponsorPlan: 155, target: 165 },
    { month: 11, p10: 118, p50: 170, p90: 229, ciLow: 108, ciHigh: 241, sponsorPlan: 175, target: 186 },
    { month: 12, p10: 134, p50: 191, p90: 255, ciLow: 124, ciHigh: 268, sponsorPlan: 194, target: 207 },
    { month: 13, p10: 152, p50: 213, p90: 281, ciLow: 141, ciHigh: 295, sponsorPlan: 214, target: 228 },
    { month: 14, p10: 170, p50: 235, p90: 307, ciLow: 158, ciHigh: 321, sponsorPlan: 235, target: 250 },
    { month: 15, p10: 189, p50: 257, p90: 320, ciLow: 176, ciHigh: 320, sponsorPlan: 255, target: 272 },
    { month: 16, p10: 208, p50: 279, p90: 320, ciLow: 195, ciHigh: 320, sponsorPlan: 275, target: 293 },
    { month: 17, p10: 228, p50: 300, p90: 320, ciLow: 214, ciHigh: 320, sponsorPlan: 296, target: 310 },
    { month: 18, p10: 248, p50: 320, p90: 320, ciLow: 234, ciHigh: 320, sponsorPlan: 316, target: 320 },
    { month: 19, p10: 268, p50: 320, p90: 320, ciLow: 254, ciHigh: 320, sponsorPlan: 320, target: 320 },
    { month: 20, p10: 288, p50: 320, p90: 320, ciLow: 274, ciHigh: 320, sponsorPlan: 320, target: 320 },
    { month: 21, p10: 308, p50: 320, p90: 320, ciLow: 294, ciHigh: 320, sponsorPlan: 320, target: 320 },
    { month: 22, p10: 320, p50: 320, p90: 320, ciLow: 306, ciHigh: 320, sponsorPlan: 320, target: 320 },
  ],
  seed: {
    runs: 1000,
    lastRunAt: "2026-06-24T09:14:00Z",
  },
  levers: [
    { id: "sites",        label: "Sites activated",     kind: "slider",  value: 28, min: 10, max: 50, step: 1, unit: "sites" },
    { id: "uk_alloc",     label: "UK allocation",       kind: "slider",  value: 55, min: 20, max: 80, step: 5, unit: "%" },
    { id: "screen_fail",  label: "Screen-failure rate", kind: "slider",  value: 38, min: 20, max: 60, step: 1, unit: "%" },
    { id: "adaptive",     label: "Adaptive interim",    kind: "toggle",  value: 0 },
    { id: "nihr",         label: "NIHR portfolio",      kind: "toggle",  value: 1 },
    { id: "dct",          label: "DCT elements",        kind: "toggle",  value: 0 },
    { id: "stipend",      label: "Patient stipend",     kind: "toggle",  value: 0 },
  ],
  sites: [
    { id: "s01", name: "Royal Free Hospital",          city: "London",     country: "UK",  region: "UK", projectedPerMonth: 4.2 },
    { id: "s02", name: "Edinburgh Royal Infirmary",    city: "Edinburgh",  country: "UK",  region: "UK", projectedPerMonth: 3.8 },
    { id: "s03", name: "Manchester University NHS FT", city: "Manchester", country: "UK",  region: "UK", projectedPerMonth: 3.5 },
    { id: "s04", name: "King's College Hospital",      city: "London",     country: "UK",  region: "UK", projectedPerMonth: 3.1 },
    { id: "s05", name: "Charité – BIH",                city: "Berlin",     country: "DE",  region: "EU", projectedPerMonth: 2.9 },
    { id: "s06", name: "Amsterdam UMC",                city: "Amsterdam",  country: "NL",  region: "EU", projectedPerMonth: 2.7 },
    { id: "s07", name: "Hôpital Beaujon",              city: "Paris",      country: "FR",  region: "EU", projectedPerMonth: 2.4 },
    { id: "s08", name: "MUSC Health",                  city: "Charleston", country: "US",  region: "US", projectedPerMonth: 3.6 },
    { id: "s09", name: "UT Southwestern Medical Ctr",  city: "Dallas",     country: "US",  region: "US", projectedPerMonth: 3.3 },
    { id: "s10", name: "Mayo Clinic",                  city: "Rochester",  country: "US",  region: "US", projectedPerMonth: 3.0 },
    { id: "s11", name: "UCSF Medical Center",          city: "San Francisco", country: "US", region: "US", projectedPerMonth: 2.8 },
    { id: "s12", name: "Hospital Clínic Barcelona",    city: "Barcelona",  country: "ES",  region: "EU", projectedPerMonth: 2.2 },
  ],
  competingTrials: [
    { nct: "NCT04990908", sponsor: "Madrigal Pharma",  n: 700,  enrolledPct: 82, phase: "Phase III", indication: "NASH F2–F3", dataAsOf: "2026-06-01" },
    { nct: "NCT05020496", sponsor: "Gilead Sciences",  n: 960,  enrolledPct: 61, phase: "Phase III", indication: "NASH F2–F3", dataAsOf: "2026-06-01" },
    { nct: "NCT05096715", sponsor: "Novo Nordisk",     n: 1200, enrolledPct: 44, phase: "Phase III", indication: "NASH F2–F3", dataAsOf: "2026-06-01" },
    { nct: "NCT05312372", sponsor: "AstraZeneca",      n: 480,  enrolledPct: 29, phase: "Phase II",  indication: "NASH F2–F3", dataAsOf: "2026-06-01" },
    { nct: "NCT05481567", sponsor: "Pfizer",           n: 320,  enrolledPct: 18, phase: "Phase II",  indication: "NASH F2–F3", dataAsOf: "2026-06-01" },
  ],
};

// ── Competitive Intelligence (S13) ───────────────────────────────────────────

export const MOCK_INTEL_NASH: IntelData = {
  indication: "NASH / MASH",
  therapeuticArea: "Hepatology",
  outlookMonths: 18,
  summary:
    "Tracking 47 active trials, 4 approved therapies, 3 milestones impacting your MAP-204 programme in the next 6 months.",
  kpis: {
    activeTrials: 47,
    activeTrialsDelta: 3,
    newApproval: "Resmetirom · first FDA approval",
    poolOverlapPct: 62,
    poolOverlapLabel: "High",
    siteCollisions: 14,
    totalSites: 28,
    regMilestones: 3,
    dataAsOf: "2026-06-01",
  },
  competingTrials: [
    { nct: "NCT04990908", name: "Resmetirom (Rezdiffra)",    sponsor: "Madrigal Pharma",  phase: "Phase III", n: 700,  enrolledPct: 82, threat: "high",   ukOverlap: true,  dataAsOf: "2026-06-01" },
    { nct: "NCT05020496", name: "Firsocostat + Semaglutide", sponsor: "Gilead Sciences",  phase: "Phase III", n: 960,  enrolledPct: 61, threat: "high",   ukOverlap: true,  dataAsOf: "2026-06-01" },
    { nct: "NCT05096715", name: "CagriSema",                 sponsor: "Novo Nordisk",     phase: "Phase III", n: 1200, enrolledPct: 44, threat: "high",   ukOverlap: false, dataAsOf: "2026-06-01" },
    { nct: "NCT05312372", name: "Zibotentan",                sponsor: "AstraZeneca",      phase: "Phase II",  n: 480,  enrolledPct: 29, threat: "medium", ukOverlap: true,  dataAsOf: "2026-06-01" },
    { nct: "NCT05481567", name: "PF-06863135",               sponsor: "Pfizer",           phase: "Phase II",  n: 320,  enrolledPct: 18, threat: "medium", ukOverlap: false, dataAsOf: "2026-06-01" },
    { nct: "NCT05800782", name: "IMM-124E",                  sponsor: "Immuron",          phase: "Phase II",  n: 160,  enrolledPct: 7,  threat: "low",    ukOverlap: false, dataAsOf: "2026-06-01" },
    { nct: "NCT06100224", name: "AZD9550",                   sponsor: "AstraZeneca",      phase: "Phase II",  n: 240,  enrolledPct: 4,  threat: "low",    ukOverlap: false, dataAsOf: "2026-06-01" },
  ],
  labelDecisions: [
    { id: "ld1", drug: "Resmetirom (Rezdiffra)",  authority: "FDA",  decision: "Approved",              date: "2024-03-14" },
    { id: "ld2", drug: "Semaglutide (NASH ind.)", authority: "EMA",  decision: "Under review",          date: "2025-11-02" },
    { id: "ld3", drug: "Lanifibranor",            authority: "EMA",  decision: "CHMP positive opinion", date: "2025-08-19" },
    { id: "ld4", drug: "Elafibranor (Iqirvo)",    authority: "MHRA", decision: "Authorised",            date: "2025-04-07" },
  ],
  cliffWatch: [
    { id: "cw1", drug: "Resmetirom US",     kind: "patent",      date: "2028-06-15", daysUntil: 720  },
    { id: "cw2", drug: "Lanifibranor EP3",  kind: "exclusivity", date: "2027-11-30", daysUntil: 523  },
    { id: "cw3", drug: "Obeticholic acid",  kind: "exclusivity", date: "2026-09-01", daysUntil: 68   },
    { id: "cw4", drug: "Elafibranor EU",    kind: "exclusivity", date: "2033-04-07", daysUntil: 2507 },
  ],
  siteOverlap: {
    yourSites:        ["Royal Free", "Edinburgh Royal", "Manchester UHFT", "King's College"],
    competitors:      ["NCT04990908", "NCT05020496", "NCT05096715"],
    competitorNames:  ["Resmetirom (Madrigal)", "Firsocostat (Gilead)", "CagriSema (Novo)"],
    cells: [
      [3, 2, 2, 1],
      [2, 1, 2, 2],
      [1, 0, 1, 0],
    ],
    atRiskCount: 3,
  },
};

// ── Regulatory Writing (S10) ──────────────────────────────────────────────────

export const MOCK_REG_WRITING_DOC: RegWritingDoc = {
  id: "doc_ind019_274",
  projectCode: "IND-019",
  projectTitle: "Onaplazib",
  docType: "CTD_2_7",
  moduleNumber: "2.7",
  sectionNumber: "2.7.4",
  sectionHeading: "Summary of Clinical Safety",
  version: "v3",
  editCount: 14,
  lastEditedBy: "Priya Shah",
  lastEditedAgo: "12 min ago",
  status: "IN_REVIEW",
  contentHash: "sha256:4a9f2c1e8b3d7f0e5c2a6b9d1e4f7c0a3b6d9e2f5a8c1b4e7f0a3d6c9b2e5f8a1",
  contentJson: {
    type: "doc",
    content: [
      {
        type: "paragraph",
        content: [
          {
            type: "text",
            text: "Onaplazib was administered to 198 patients with NASH fibrosis stages F2–F3 across the MAP-204 Phase II study. The overall safety profile was characterised by a low rate of serious adverse events (SAEs) and no dose-limiting toxicities at the 40 mg once-daily dose level. ",
          },
          { type: "citation", attrs: { n: 2, label: "CSR", sourceId: "src_csr_001" } },
          { type: "citation", attrs: { n: 4, label: "CSR", sourceId: "src_csr_002" } },
        ],
      },
      {
        type: "paragraph",
        content: [
          {
            type: "text",
            text: "Treatment-emergent adverse events (TEAEs) were reported in 74.2% of patients in the onaplazib 40 mg arm versus 68.9% in the placebo arm. The most common TEAEs (≥5% in either arm) were nausea (14.1% vs 9.8%), headache (11.6% vs 10.2%), and fatigue (9.6% vs 11.4%). The integrated safety summary across the MAP-204 programme supports a favourable benefit–risk profile consistent with published Phase II NASH precedents. ",
          },
          { type: "citation", attrs: { n: 11, label: "ISS", sourceId: "src_iss_001" } },
          { type: "citation", attrs: { n: 13, label: "ISS", sourceId: "src_iss_002" } },
        ],
      },
      {
        type: "paragraph",
        content: [
          {
            type: "text",
            text: "Hepatic safety was closely monitored in line with FDA guidance on DILI assessment. ALT elevations ≥3× ULN were observed in 3.5% of onaplazib-treated patients, all resolving within 4 weeks of dose interruption, with no cases meeting Hy's Law criteria. ",
          },
          { type: "citation", attrs: { n: 20, label: "FDA·DILI", sourceId: "src_fda_dili" } },
          { type: "citation", attrs: { n: 7, label: "DSUR", sourceId: "src_dsur_001" } },
        ],
      },
      {
        type: "paragraph",
        content: [
          {
            type: "text",
            text: "Cardiac safety was evaluated per ICH E14 guidelines with centralised QTcF analysis. No clinically meaningful QTcF prolongation was observed (mean ΔQTcF = +2.1 ms; upper 90% CI = +4.7 ms), with no subjects exceeding 500 ms or demonstrating ΔQTcF > 60 ms. ",
          },
          { type: "citation", attrs: { n: 15, label: "ICH E14", sourceId: "src_ich_e14" } },
        ],
      },
    ],
  },
  citations: [
    { n: 2,  sourceId: "src_csr_001",  label: "CSR",      authority: "Internal", title: "MAP-204 Clinical Study Report v1.2",                    kind: "CSR" },
    { n: 4,  sourceId: "src_csr_002",  label: "CSR",      authority: "Internal", title: "MAP-204 CSR Appendix 14.3 — AE Listings",                kind: "CSR" },
    { n: 7,  sourceId: "src_dsur_001", label: "DSUR",     authority: "Internal", title: "MAP-204 Development Safety Update Report Year 2",         kind: "DSUR" },
    { n: 11, sourceId: "src_iss_001",  label: "ISS",      authority: "Internal", title: "Integrated Summary of Safety — Module 5.3.5.1",           kind: "ISS" },
    { n: 13, sourceId: "src_iss_002",  label: "ISS",      authority: "Internal", title: "ISS Appendix B — Subgroup Safety Analysis",               kind: "ISS" },
    { n: 15, sourceId: "src_ich_e14",  label: "ICH E14",  authority: "ICH",      title: "ICH E14 Guideline — QT/QTc Interval Evaluation",         kind: "Guideline" },
    { n: 20, sourceId: "src_fda_dili", label: "FDA·DILI", authority: "FDA",      title: "FDA Guidance — Drug-Induced Liver Injury (2009)",         kind: "Guidance" },
  ],
  aiDraftBlock: {
    id: "aib_274_renal",
    text: "Renal safety: No clinically meaningful changes in eGFR were observed in onaplazib-treated patients at 40 mg (mean change from baseline: −1.2 mL/min/1.73 m²; 95% CI: −2.8 to +0.4). Incidence of adverse events of special interest for renal function (eGFR decline ≥30%) was 1.5% vs 2.0% in placebo, consistent with background rates in NASH F2–F3 populations reported in precedent Phase II programmes.",
    confidence: 0.81,
    sourceCount: 5,
    modelVersion: "cohortly-v3",
    status: "pending",
  },
  comments: [
    {
      id: "cmt_001",
      author: "James Hartley",
      authorInitials: "JH",
      role: "QA Reviewer",
      body: "SAE incidence reported here as 3.5% — confirm alignment with §5.3.5.1 ISS table which shows 3.8%. Needs reconciliation before sign-off.",
      timestamp: "2026-06-24 09:14",
      kind: "human",
      resolved: false,
    },
    {
      id: "cmt_002",
      author: "Priya Shah",
      authorInitials: "PS",
      role: "RA Lead",
      body: "The 3.5% figure excludes one site (ERI) which had a data-lock anomaly. ISS was updated to 3.5% in v1.3 — ISS reference here is pointing to v1.2. Updating citation.",
      timestamp: "2026-06-24 11:02",
      kind: "human",
      resolved: false,
    },
    {
      id: "cmt_003",
      author: "Cohortly AI",
      authorInitials: "AI",
      role: "AI Assistant",
      body: "Detected: citation [11] links to ISS v1.2 (src_iss_001). Current version in KB is v1.3. Suggest updating source reference to resolve consistency check flag.",
      timestamp: "2026-06-24 11:05",
      kind: "ai",
      confidence: 0.94,
      resolved: false,
    },
  ],
  history: [
    { id: "h1", actor: "Cohortly AI",  actorInitials: "AI", action: "Generated §2.7.4 draft (14 sources, confidence 0.84)", timestamp: "2026-06-23 15:30", kind: "ai" },
    { id: "h2", actor: "Priya Shah",   actorInitials: "PS", action: "Accepted hepatic safety paragraph; edited TEAE table",  timestamp: "2026-06-23 16:45", kind: "human" },
    { id: "h3", actor: "James Hartley",actorInitials: "JH", action: "Submitted for QA review",                               timestamp: "2026-06-24 08:55", kind: "human" },
    { id: "h4", actor: "System",       actorInitials: "SY", action: "Consistency check flagged ISS version mismatch",         timestamp: "2026-06-24 09:00", kind: "system" },
    { id: "h5", actor: "Priya Shah",   actorInitials: "PS", action: "Replied to comment cmt_001; citation update pending",   timestamp: "2026-06-24 11:02", kind: "human" },
  ],
  modules: [
    {
      id: "m1", number: "1", heading: "Regional & Administrative", status: "draft", children: [],
    },
    {
      id: "m2", number: "2", heading: "Common Technical Document Summaries", status: "draft",
      children: [
        { id: "m23", number: "2.3", heading: "Quality Overall Summary",         status: "complete" },
        { id: "m24", number: "2.4", heading: "Nonclinical Overview",            status: "complete" },
        { id: "m25", number: "2.5", heading: "Clinical Overview",               status: "review" },
        {
          id: "m27", number: "2.7", heading: "Clinical Summaries", status: "draft",
          children: [
            { id: "m271", number: "2.7.1", heading: "Summary of Biopharmaceutic Studies",   status: "complete" },
            { id: "m272", number: "2.7.2", heading: "Summary of Clinical Pharmacology",     status: "complete" },
            { id: "m273", number: "2.7.3", heading: "Summary of Clinical Efficacy",         status: "review" },
            { id: "m274", number: "2.7.4", heading: "Summary of Clinical Safety",           status: "draft" },
            { id: "m275", number: "2.7.5", heading: "References",                           status: "empty" },
          ],
        },
      ],
    },
    {
      id: "m3", number: "3", heading: "Quality", status: "complete", children: [],
    },
    {
      id: "m4", number: "4", heading: "Nonclinical Study Reports", status: "complete", children: [],
    },
    {
      id: "m5", number: "5", heading: "Clinical Study Reports", status: "review", children: [],
    },
  ],
  consistencyIssues: [
    {
      id: "ci1",
      kind: "cross-module",
      label: "SAE % mismatch",
      severity: "error",
      detail: "§2.7.4 reports 3.5% vs ISS §5.3.5.1 which shows 3.8% — reconcile before sign-off.",
    },
    {
      id: "ci2",
      kind: "reference",
      label: "ISS version mismatch",
      severity: "warning",
      detail: "Citation [11] links to ISS v1.2; current version is v1.3.",
    },
    {
      id: "ci3",
      kind: "terminology",
      label: "TEAE not MedDRA-mapped",
      severity: "warning",
      detail: "\"fatigue\" in §2.7.4 para 2 not mapped to preferred MedDRA PT (Fatigue, MedDRA 10016256).",
    },
    {
      id: "ci4",
      kind: "numbering",
      label: "Numbering OK",
      severity: "ok",
      detail: "All section and table numbers are consistent across modules.",
    },
  ],
  docHealth: [
    { label: "Source-traceable",  value: 88, target: 90 },
    { label: "Terminology",       value: 74, target: 95 },
    { label: "SPIRIT",            value: 91, target: 85 },
    { label: "Plain-English",     value: 38, target: 35, unit: "Flesch" },
  ],
};

// ── Safety & Pharmacovigilance (S12) ─────────────────────────────────────────

export const MOCK_SAFETY_CASE: SafetyCase = {
  id: "sae_1142",
  saeRef: "SAE-1142",
  subjectRef: "04-218",
  projectCode: "MAP-204",
  siteCode: "UK-04",
  studyDrug: "onaplazib",
  studyDose: "60 mg",
  expedited: true,
  isSusar: true,
  clock: {
    clockType: "15-day",
    daysRemaining: 3,
    hoursRemaining: 4,
    dueDate: "2026-06-28",
    overdue: false,
  },
  status: "awaiting-sign-off",
  demographics: {
    sex: "Female",
    age: 38,
    ethnicity: "White",
    bmi: 29.4,
    nasScore: "6.1",
    fibrosisStage: "F2",
  },
  event: {
    pt: "Febrile neutropenia",
    ptCode: "10016288",
    soc: "Blood and lymphatic system disorders",
    onsetDate: "Day 34",
    severity: "severe",
    outcome: "recovering",
    causality: "probable",
  },
  concomitantMeds: [
    { name: "Metformin", dose: "1g BD", indication: "Type 2 diabetes" },
    { name: "Furosemide", dose: "40 mg OD", indication: "Hypertension" },
    { name: "Atorvastatin", dose: "10 mg OD", indication: "Dyslipidaemia" },
    { name: "Lorazepam", dose: "1 mg PRN", indication: "Anxiety" },
    { name: "Prescribed PPI", dose: "Omeprazole 20 mg", indication: "GI protection" },
  ],
  relevantHistory: [
    { condition: "Type 2 diabetes mellitus", year: 2018 },
    { condition: "Hypertension", year: 2015 },
    { condition: "No prior chemotherapy", year: 0 },
  ],
};

export const MOCK_SAFETY_NARRATIVE: SafetyNarrative = {
  id: "narr_1142",
  caseId: "sae_1142",
  status: "pending",
  confidence: 0.87,
  sourceFieldCount: 9,
  templateVersion: "3.1",
  modelVersion: "cohortly-v3",
  paragraphs: [
    {
      id: "p1",
      text: "Subject 04-218 is a 38-year-old White British female with a baseline diagnosis of non-alcoholic steatohepatitis (NAS 6, fibrosis stage F2) and concomitant type 2 diabetes mellitus and hypertension, randomised on 14 April 2026 to receive onaplazib 60 mg once daily.",
      highlights: [
        { text: "38-year-old White British female", field: "DEMOGRAPHICS" },
        { text: "NAS 6, fibrosis stage F2", field: "NAS·FIBROSIS" },
        { text: "onaplazib 60 mg once daily", field: "STUDY DRUG" },
      ],
    },
    {
      id: "p2",
      text: "On Day 34 of study treatment, the subject presented to her local emergency department with a 24-hour history of fever (38.1°C), rigors, and fatigue. Laboratory evaluation revealed an absolute neutrophil count of 0.4 × 10⁹/L (baseline 3.8 × 10⁹/L) and CRP of 142 mg/L. Blood cultures were obtained and subsequently grew Escherichia coli sensitive to piperacillin–tazobactam.",
      highlights: [
        { text: "fever (38.1°C)", field: "TEMP" },
        { text: "rigors", field: "SYMPTOM" },
        { text: "fatigue", field: "SYMPTOM" },
      ],
    },
    {
      id: "p3",
      text: "The event was assessed as Grade 3 febrile neutropenia (MedDRA PT 10016288) by the investigator and confirmed by the independent Data Safety Monitoring Board. Study drug was permanently discontinued on Day 35 per protocol M4.4 stopping rules. The subject was admitted for intravenous antibiotics and G-CSF support. By Day 41, ANC had recovered to 1.6 × 10⁹/L and the subject was discharged in stable condition.",
      highlights: [
        { text: "Grade 3 febrile neutropenia (MedDRA PT 10016288)", field: "MEDDRA PT" },
      ],
    },
    {
      id: "p4",
      text: "The investigator assessed the relationship to study drug as probable, citing temporal association and the known mechanism of onaplazib's class effect on myeloid progenitors. No alternative aetiology was identified. The event is considered a Suspected Serious Adverse Reaction (SUSAR) — it is not listed in the current Investigator's Brochure (v4, §5.2.1).",
      highlights: [
        { text: "probable", field: "CAUSALITY" },
      ],
    },
    {
      id: "p5",
      text: "As of the data lock point (08 May 2026), the subject is recovering with sequelae. Follow-up is scheduled at 30 and 60 days post-event.",
      highlights: [],
    },
  ],
  footerMetrics: [
    { label: "Reporting clock", value: "12d to file" },
    { label: "Template adherence", value: "12 of 12 sections" },
    { label: "MedDRA accuracy", value: "100% mapped" },
    { label: "Regulatory destinations", value: "MHRA · FDA · EMA" },
  ],
  timelineEntries: [
    { date: "14 Apr 2026", event: "Randomisation", detail: "onaplazib 60 mg OD commenced" },
    { date: "17 May 2026 (Day 34)", event: "AE onset", detail: "Fever 38.1°C, rigors, fatigue; ANC 0.4 × 10⁹/L", flagged: true },
    { date: "18 May 2026 (Day 35)", event: "Drug discontinued", detail: "Per M4.4 stopping rules; IV antibiotics + G-CSF started" },
    { date: "24 May 2026 (Day 41)", event: "ANC recovery", detail: "ANC 1.6 × 10⁹/L; subject discharged in stable condition" },
    { date: "08 Jun 2026", event: "Follow-up planned", detail: "30-day and 60-day post-event checks scheduled" },
  ],
  labRows: [
    { test: "ANC (× 10⁹/L)",   baseline: "3.8",  day14: "3.6",  day28: "3.1",  day41: "1.6",  unit: "× 10⁹/L", flagged: true },
    { test: "Hb (g/dL)",        baseline: "12.8", day14: "12.4", day28: "11.9", day41: "12.1", unit: "g/dL" },
    { test: "Platelets (× 10⁹/L)", baseline: "210", day14: "198", day28: "185", day41: "210",  unit: "× 10⁹/L" },
    { test: "CRP (mg/L)",       baseline: "4.2",  day14: "5.1",  day28: "8.4",  day41: "142",  unit: "mg/L", flagged: true },
    { test: "ALT (U/L)",        baseline: "28",   day14: "31",   day28: "29",   day41: "35",   unit: "U/L" },
    { test: "eGFR (mL/min)",    baseline: "88",   day14: "85",   day28: "82",   day41: "80",   unit: "mL/min" },
  ],
};

export const MOCK_NARRATIVE_QUEUE: QueueCase[] = [
  {
    id: "sae_1142",
    saeRef: "SAE-1142",
    subjectRef: "04-218",
    meddraPt: "Febrile neutropenia",
    clockType: "15-day",
    daysRemaining: 3,
    hoursRemaining: 4,
    overdue: false,
    confidence: 0.87,
    status: "awaiting-sign-off",
  },
  {
    id: "sae_0362",
    saeRef: "SAE-0362",
    subjectRef: "02-091",
    meddraPt: "ALT increased",
    clockType: "15-day",
    daysRemaining: 8,
    hoursRemaining: 2,
    overdue: false,
    confidence: 0.91,
    status: "open",
  },
  {
    id: "sae_0448",
    saeRef: "SAE-0448",
    subjectRef: "07-312",
    meddraPt: "Atrial fibrillation",
    clockType: "7-day",
    daysRemaining: 0,
    hoursRemaining: 0,
    overdue: true,
    confidence: 0.74,
    status: "overdue",
  },
  {
    id: "sae_0519",
    saeRef: "SAE-0519",
    subjectRef: "03-147",
    meddraPt: "Pneumonia",
    clockType: "15-day",
    daysRemaining: 12,
    hoursRemaining: 6,
    overdue: false,
    confidence: 0.83,
    status: "open",
  },
  {
    id: "sae_0611",
    saeRef: "SAE-0611",
    subjectRef: "05-229",
    meddraPt: "Neutropenia",
    clockType: "15-day",
    daysRemaining: 14,
    hoursRemaining: 0,
    overdue: false,
    confidence: 0.79,
    status: "open",
  },
];

export const MOCK_SAFETY_SIGNALS: SafetySignal[] = [
  {
    id: "sig_001",
    term: "Neutropenia",
    assessment: "possible",
    observed: 4,
    expected: 1,
    prr: 4.2,
    chiSquared: 8.9,
    detail: "Febrile neutropenia n=4 vs IB expected n≤1",
  },
  {
    id: "sig_002",
    term: "Hepatotoxicity",
    assessment: "possible",
    observed: 2,
    expected: 1,
    prr: 2.1,
    chiSquared: 3.4,
    detail: "ALT ≥3× ULN: n=2; monitoring ongoing per DILI protocol",
  },
];

export const MOCK_CUMULATIVE_SAFETY: CumulativeSafety = {
  projectCode: "MAP-204",
  totalSaes: 5,
  totalSusars: 2,
  dsurDue: "15 Aug",
  dsmbNext: "11 Jun",
};

// ── Ethics & IRAS Assistant (S11) ─────────────────────────────────────────────

export const MOCK_ETHICS_APPLICATION: EthicsApplication = {
  id: "eth_map204_001",
  irasId: "IRAS-2024-089432",
  version: "v2.3",
  completionPct: 68,
  projectCode: "MAP-204",
  projectTitle: "Onaplazib in NASH",
  jurisdiction: "UK",
  authority: "HRA / IRAS",
};

export const MOCK_ETHICS_SECTIONS: FormSection[] = [
  { id: "sec_a", code: "A", title: "Project details", answeredCount: 16, totalCount: 16, status: "complete" },
  { id: "sec_b", code: "B", title: "Sponsor / CI", answeredCount: 8, totalCount: 8, status: "complete" },
  { id: "sec_c", code: "C", title: "Protocol & study design", answeredCount: 10, totalCount: 12, status: "in-progress" },
  {
    id: "sec_d",
    code: "D",
    title: "Participants & recruitment",
    answeredCount: 14,
    totalCount: 17,
    status: "in-progress",
    answers: [
      {
        id: "ans_d1",
        questionCode: "D1",
        question: "What is the total number of participants in the UK sites?",
        answer: "A total of 180 participants will be enrolled across 14 UK sites, forming part of the global target of 320. Randomisation is 2:1 (onaplazib : placebo) stratified by fibrosis stage (F2 vs F3) and diabetes status.",
        kind: "auto",
        sourceRef: "Protocol §3.4",
        confidence: 0.98,
      },
      {
        id: "ans_d2",
        questionCode: "D2",
        question: "What is the planned duration of the recruitment period?",
        answer: "Recruitment is planned over 18 months (March 2024 – August 2025) with an expected screen failure rate of 38%. Site activation across UK will be staggered over Q1 2024.",
        kind: "auto",
        sourceRef: "Protocol §2.1",
        confidence: 0.92,
      },
      {
        id: "ans_d3",
        questionCode: "D3",
        question: "Please summarise the inclusion criteria.",
        answer: "Adults aged 18–75 years with biopsy-confirmed NASH (NAS ≥4 with fibrosis score F2–F3), BMI 25–45 kg/m², and written informed consent. Full SPIRIT-compliant criteria are detailed in Protocol §5.1.",
        kind: "auto",
        sourceRef: "Protocol §5.1",
        confidence: 0.87,
      },
      {
        id: "ans_d4",
        questionCode: "D4",
        question: "Please summarise the exclusion criteria.",
        answer: "Prior hepatic decompensation, Child-Pugh B/C, active HBV/HCV, pregnancy or breastfeeding, eGFR <30 mL/min/1.73 m², or any condition that, in the investigator's judgement, would preclude safe participation. See Protocol §5.2 for the complete list (22 criteria).",
        kind: "edited",
        sourceRef: "Protocol §5.2",
        confidence: 0.84,
      },
    ],
    pisReadability: {
      plainEnglish: true,
      readingAge: 11.4,
      fleschScore: 58.2,
      wordCount: 847,
      sectionCount: 6,
      hraTemplateVersion: "HRA PIS v3.2",
    },
  },
  { id: "sec_e", code: "E", title: "Research procedures", answeredCount: 6, totalCount: 9, status: "draft" },
  { id: "sec_f", code: "F", title: "Finance & insurance", answeredCount: 4, totalCount: 8, status: "draft" },
  { id: "sec_g", code: "G", title: "Indemnity", answeredCount: 3, totalCount: 4, status: "draft" },
  { id: "sec_h", code: "H", title: "Declarations", answeredCount: 0, totalCount: 5, status: "empty" },
];

export const MOCK_REQUIRED_DOCS: RequiredDoc[] = [
  { id: "doc_protocol",   label: "Protocol",                  detail: "v2.1 — 2026-05-14",     status: "submitted"    },
  { id: "doc_ib",         label: "Investigator's Brochure",   detail: "v4 — 2026-04-01",       status: "submitted"    },
  { id: "doc_pis_adult",  label: "PIS (adult)",               detail: "In review",             status: "in-progress"  },
  { id: "doc_icf_adult",  label: "ICF (adult)",               detail: "Awaiting PIS sign-off", status: "in-progress"  },
  { id: "doc_gp_letter",  label: "GP letter template",        detail: "Draft prepared",        status: "draft"        },
  { id: "doc_dpia",       label: "DPIA",                      detail: "Required for UK GDPR",  status: "missing"      },
  { id: "doc_insurance",  label: "Sponsor insurance cert.",   detail: "Confirmed",             status: "submitted"    },
];

export const MOCK_HRA_CHECKS: HraCheck[] = [
  { id: "hra1", framework: "UK Policy Framework for Health & Social Care Research", status: "pass" },
  { id: "hra2", framework: "Equality Act 2010", status: "pass" },
  { id: "hra3", framework: "Inclusion & Diversity Guidance 2022", status: "warn", note: "Recruitment target includes <30% female — document diversity rationale in section D." },
  { id: "hra4", framework: "Data Protection Act 2018 / UK GDPR", status: "warn", note: "DPIA not submitted. Required before HRA opinion can be issued." },
  { id: "hra5", framework: "Mental Capacity Act 2005", status: "n-a" },
];

export const MOCK_HRA_GAP: HraGap = {
  message: "DPIA missing in section F12 — required for UK GDPR. Generate from protocol →",
  sectionRef: "F12",
  action: "Generate from protocol",
};

export const MOCK_REC_TIMELINE: RecMilestone[] = [
  { id: "ms1", label: "Submission",    date: "1 Jul 2026",  status: "upcoming" },
  { id: "ms2", label: "Validation",   date: "15 Jul 2026", status: "upcoming" },
  { id: "ms3", label: "REC meeting",  date: "5 Aug 2026",  status: "upcoming" },
  { id: "ms4", label: "Opinion",      date: "9 Aug 2026",  status: "upcoming" },
  { id: "ms5", label: "HRA approval", date: "23 Aug 2026", status: "upcoming" },
];

export const MOCK_NIHR_PORTFOLIO: NihrPortfolio = {
  eligible: true,
  studyType: "Clinical trial of medicinal product",
  category: "Hepatology / NASH",
  adopted: false,
};

